/**
 * The single source of CBA numbers for the engine. Values come from data/cba.json (generated by
 * scripts/fetch-data.ts). A league stores its own copy so commissioner edits and future-season cap
 * growth apply per save. Never hard-code a CBA figure elsewhere - read it from a `Cba`.
 */
import raw from "../../../data/cba.json";

type Widen<T> = T extends number ? number : T extends string ? string : T extends boolean ? boolean : T extends readonly (infer U)[] ? Widen<U>[] : T extends object ? { -readonly [K in keyof T]: Widen<T[K]> } : T;
export type Cba = Widen<typeof raw>;

export const DEFAULT_CBA: Cba = raw as Cba;

export function cloneCba(c: Cba): Cba {
  return JSON.parse(JSON.stringify(c)) as Cba;
}

const r = (v: number, f: number) => Math.round(v * f);

/**
 * Project the CBA to the next league year: every dollar threshold grows with the cap (the CBA indexes
 * them to cap growth). Returns a new object; the original is untouched.
 */
export function projectCba(c: Cba, growth: number, season: string): Cba {
  const n = cloneCba(c);
  const f = 1 + growth;
  n.season = season;
  n.status = "projected";
  for (const k of ["salaryCap", "minimumTeamSalary", "luxuryTax", "firstApron", "secondApron", "averageSalaryEstimate"] as const) {
    n[k].value = r(n[k].value, f);
    n[k].verified = false;
  }
  const ex = n.exceptions;
  for (const k of ["nonTaxpayerMLE", "taxpayerMLE", "roomMLE", "biAnnual", "earlyBirdMaxStart", "expandedTpeAllowance", "tradeCashLimit", "exhibit10MaxBonus", "twoWaySalary"] as const) {
    ex[k].value = r(ex[k].value, f);
  }
  n.tax.bracketSize = r(n.tax.bracketSize, f);
  n.maxSalary.byService = n.maxSalary.byService.map((b) => ({ ...b, value: Math.round(n.salaryCap.value * b.pct) }));
  n.minimumSalary.byService = n.minimumSalary.byService.map((v) => r(v, f));
  n.minimumSalary.oneYearVetCapHit = n.minimumSalary.byService[2];
  n.rookieScale.pct120 = n.rookieScale.pct120.map((row) => row.map((v) => r(v, f)));
  n.rookieScale.pct100 = n.rookieScale.pct100.map((row) => row.map((v) => r(v, f)));
  n.trade.nonApron.allowance = ex.expandedTpeAllowance.value;
  return n;
}
