// Floodlights unexpected events. Each club rolls once a week (at most one event a week).
// t: the news line ({p} is the player hit, {q} a second one, {n} how many, {d} the injury length).
// who: one, few, squad or gk. h: a short headline for the popup (the newer events have one).
// f: form change, m: morale change. w: how long it lasts in matches (1 one match, 3 a few, 0 lingering, which
// moves the player's own form and morale for good instead of a short effect).
// inj: weeks out for an off the pitch injury, a number or [min, max]. It goes through the normal injury
// system (out, then the return knock), and a head physio takes a week off.
const EVENTS = [
  // ---------- travel and hotel trouble ----------
  { t: "{p} got left at the hotel before the game. The bus went without him. Squad morale down for the match.", who: "squad", m: -0.5, w: 1 },
  { t: "Away fans let off firecrackers outside the team hotel all night. {n} players are shattered and their form is down.", who: "few", f: -1, w: 1 },
  { t: "The hotel double booked the rooms and half the squad shared beds. Nobody slept. Form down for a match.", who: "squad", f: -1, w: 1 },
  { t: "The team bus broke down on the motorway. The lads arrived ninety minutes before kick off and stiff as boards.", who: "squad", f: -1, w: 1 },
  { t: "A fire alarm went off at 3am and the whole squad stood in the car park in their pants. Form down this week.", who: "squad", f: -1, w: 1 },
  { t: "The hotel chef served something dodgy. {p} and {q} spent the night being sick. Form down for a couple of games.", who: "few", f: -1, w: 2 },
  { t: "The flight was delayed five hours and the squad ate airport sandwiches for dinner. Morale down for the match.", who: "squad", m: -0.5, w: 1 },
  { t: "{p} lost his passport at the airport and missed the flight. He turned up a day late and rattled. Form down.", who: "one", f: -2, w: 2 },
  { t: "The hotel pool was closed for cleaning and the lads sulked about it all day. Morale down a touch.", who: "squad", m: -0.3, w: 1 },
  { t: "The hotel upgraded everyone to suites by mistake. Best night of sleep all season. Form up for the match.", who: "squad", f: 1, w: 1 },
  { t: "The hotel laid on a surprise barbecue by the pool. Good vibes all round. Squad morale up.", who: "squad", m: 0.5, w: 2 },
  { t: "{p} found a piano in the hotel lobby and played for an hour. The lads loved it. Morale up for the trip.", who: "squad", m: 0.4, w: 1 },
  { t: "The coach driver got lost and took the scenic route. The lads saw a castle. Neutral, but a nice day out.", who: "squad", m: 0.1, w: 1 },
  { t: "The team plane hit turbulence over the mountains and {p} has sworn off flying. He is a mess this week.", who: "one", f: -2, m: -0.5, w: 1 },
  { t: "{p} slept through his alarm and missed the bus to training. Fined a week's wages. Morale down.", who: "one", m: -1, w: 3 },
  { t: "A wedding party in the hotel bar sang until dawn. {n} players are running on fumes.", who: "few", f: -1, w: 1 },
  { t: "The hotel gym had no weights, just two yoga mats. The lads did a stretching session instead and felt great.", who: "squad", f: 1, w: 1 },
  { t: "The bus had no air conditioning on the hottest day of the year. Everyone arrived dripping. Form down.", who: "squad", f: -1, w: 1 },
  { t: "Someone booked the team into a hotel next to a nightclub. Thump thump thump until four. Form down.", who: "squad", f: -1, w: 1 },
  { t: "The airline lost the kit bags. The squad warmed up in borrowed training gear. Form down for the match.", who: "squad", f: -1, w: 1 },

  // ---------- family and life ----------
  { t: "{p} became a dad this week. The baby arrived early and healthy. His morale is through the roof.", who: "one", m: 2, w: 0 },
  { t: "{p} got engaged on the beach at the weekend. He is floating around training. Morale way up.", who: "one", m: 1.5, w: 0 },
  { t: "{p} got married over the international break. Big smile, big form.", who: "one", f: 1, m: 1, w: 0 },
  { t: "{p} is going through a messy break up. His head is somewhere else. Form and morale down.", who: "one", f: -2, m: -1, w: 0 },
  { t: "{p} lost his grandad this week. The squad wore black armbands. He plays, but his form is down for a bit.", who: "one", f: -2, m: -1, w: 3 },
  { t: "{p} moved house and spent three days carrying boxes. Legs heavy for a match.", who: "one", f: -1, w: 1 },
  { t: "{p} bought a dog. The whole dressing room has met the dog. Morale up for everyone.", who: "squad", m: 0.3, w: 1 },
  { t: "{p} passed his driving test at the fourth attempt. The lads have not stopped laughing. Morale up.", who: "squad", m: 0.3, w: 1 },
  { t: "{p} has a new baby at home and is getting two hours of sleep a night. Form down for a few games.", who: "one", f: -1, w: 3 },
  { t: "{p} got a surprise visit from his parents, who flew in to watch him play. Morale up.", who: "one", m: 1, w: 2 },
  { t: "{p} finished his coaching badges in the evenings. He is seeing the game differently. Form up.", who: "one", f: 1, w: 0 },
  { t: "{p} had a tooth out and his face is the size of a football. Form down for a match.", who: "one", f: -1, w: 1 },
  { t: "{p} got sunburned on his day off and cannot wear a shirt without wincing. Form down for a match.", who: "one", f: -1, w: 1 },
  { t: "{p} won a charity bake off against the kitchen staff. Nobody can believe it. Morale up.", who: "one", m: 1, w: 2 },
  { t: "{p} has had a falling out with his agent. Lots of angry phone calls. Morale down.", who: "one", m: -1, w: 0 },
  { t: "{p} got a new puppy and it chewed through his match boots. He played in borrowed ones. Form down for a match.", who: "one", f: -1, w: 1 },
  { t: "{p} celebrated his birthday with the squad. Cake, songs, a bit of a sing song. Morale up.", who: "squad", m: 0.3, w: 1 },
  { t: "{p} opened a restaurant in town and it got a glowing review. He cannot stop grinning. Morale up.", who: "one", m: 1, w: 0 },
  { t: "{p} has family visiting from home for a month. Home cooking every night. Form up.", who: "one", f: 1, w: 3 },
  { t: "{p} is homesick. He has been quiet at training all week. Morale down.", who: "one", m: -1, w: 3 },

  // ---------- dressing room ----------
  { t: "Team bonding dinner went brilliantly. Karaoke, speeches, the lot. Squad morale up.", who: "squad", m: 0.5, w: 0 },
  { t: "The team bonding paintball day ended with {p} and {q} not speaking. Morale down for both.", who: "few", m: -1, w: 3 },
  { t: "{p} did an interview trashing the coach. He and two mates in the dressing room have lost the mood.", who: "few", m: -1, w: 3 },
  { t: "The keeper did an interview trashing the coach. His morale and that of two team mates is down.", who: "gk", m: -1, w: 3 },
  { t: "The squad went go karting and {p} beat everyone. Bragging rights for a month. Morale up all round.", who: "squad", m: 0.3, w: 1 },
  { t: "A row broke out at training over a bad tackle. {p} and {q} had to be pulled apart. Morale down for both.", who: "few", m: -1, f: -1, w: 2 },
  { t: "The captain called a players only meeting after the last result. Honest words. Form up for the squad.", who: "squad", f: 1, w: 1 },
  { t: "The senior players took the youngsters out for dinner. Good for the group. Morale up.", who: "squad", m: 0.4, w: 2 },
  { t: "{p} was caught talking about his team mates in a leaked voice note. Awkward. Squad morale down.", who: "squad", m: -0.5, w: 2 },
  { t: "The squad had a five a side tournament with the staff. The chef scored a hat trick. Morale up.", who: "squad", m: 0.3, w: 1 },
  { t: "{p} has been made vice captain. He is walking taller already. Form up.", who: "one", f: 1, m: 1, w: 0 },
  { t: "{p} lost the vice captaincy after a row with the staff. Morale down.", who: "one", m: -1, w: 0 },
  { t: "A dressing room prank went too far. {p} found his car wrapped in cling film. He did not laugh.", who: "one", m: -1, w: 1 },
  { t: "A dressing room prank went down a storm. {p} filled {q}'s locker with balloons. Morale up all round.", who: "squad", m: 0.3, w: 1 },
  { t: "The squad fell out over the music in the dressing room. {p} has banned everything but jazz. Morale down.", who: "squad", m: -0.3, w: 1 },
  { t: "The squad started a group chat without the manager. Lots of jokes. Morale up a touch.", who: "squad", m: 0.2, w: 1 },
  { t: "{p} gave a fiery speech before training about standards. The lads ran through walls. Form up.", who: "squad", f: 1, w: 1 },
  { t: "{p} and {q} have become best mates and are always first out for training. Form up for both.", who: "few", f: 1, w: 3 },
  { t: "The squad is split over a card game debt. {p} says he is owed money. Morale down for a few.", who: "few", m: -0.5, w: 2 },
  { t: "Some of the lads turned up late for a team meeting and got a rollicking. Form down for them.", who: "few", f: -1, w: 1 },

  // ---------- fans and media ----------
  { t: "The fans unveiled a huge banner of {p} before training. He was close to tears. Morale up.", who: "one", m: 1, w: 3 },
  { t: "A section of the fans booed {p} after the last game. He has gone very quiet. Morale down.", who: "one", m: -1, w: 2 },
  { t: "The local paper ran a front page calling the squad lazy. The lads are furious and fired up. Form up.", who: "squad", f: 1, w: 1 },
  { t: "A pundit called {p} the most overrated player in the league. He wants to prove them wrong. Form up.", who: "one", f: 2, w: 2 },
  { t: "A pundit called {p} the most overrated player in the league. He read it and believed it. Form down.", who: "one", f: -1, m: -0.5, w: 2 },
  { t: "{p} went viral for a backheel in training. Ten million views. He is loving life. Morale up.", who: "one", m: 1, w: 2 },
  { t: "{p} went viral for falling over in training. Ten million views. He is not loving life. Morale down.", who: "one", m: -0.5, w: 1 },
  { t: "The fans sang {p}'s name for ten straight minutes in the last game. He is buzzing. Form up.", who: "one", f: 1, m: 0.5, w: 2 },
  { t: "A fan ran onto the training pitch and nutmegged {p}. The video is everywhere. The squad is howling.", who: "squad", m: 0.3, w: 1 },
  { t: "{p} was voted fans' player of the month. Morale up.", who: "one", m: 1, w: 2 },
  { t: "The club shop sold out of {p} shirts. He has signed four hundred of them this week. Morale up.", who: "one", m: 0.5, w: 2 },
  { t: "{p} got into a spat with a fan on social media. The club made him apologise. Morale down.", who: "one", m: -1, w: 2 },
  { t: "The fans held a protest about ticket prices outside training. It was loud. Squad form down for a match.", who: "squad", f: -1, w: 1 },
  { t: "A radio phone in spent an hour slating {p}. His mum rang him about it. Morale down.", who: "one", m: -1, w: 1 },
  { t: "A documentary crew has been following the squad all week. Everyone is on their best behaviour. Form up.", who: "squad", f: 1, w: 1 },
  { t: "The documentary crew caught {p} moaning about tactics. Awkward meeting with the gaffer. Morale down.", who: "one", m: -1, w: 2 },
  { t: "The fans raised money for a local hospital in {p}'s name. He visited the ward. Morale up.", who: "one", m: 1, w: 0 },
  { t: "A newspaper claimed {p} wants to leave. He says it is nonsense but the squad is unsettled. Morale down.", who: "squad", m: -0.3, w: 1 },
  { t: "The squad did a hospital visit with Christmas presents. Everyone came back humbled and happy. Morale up.", who: "squad", m: 0.4, w: 2 },
  { t: "The club mascot tripped over {p} in the tunnel and the whole stadium laughed. Nobody is bothered.", who: "one", m: 0.1, w: 1 },

  // ---------- training ----------
  { t: "The training pitch flooded and the squad trained in a car park. Form down for the match.", who: "squad", f: -1, w: 1 },
  { t: "{p} has been staying behind after training every day to practise free kicks. Form up.", who: "one", f: 1, w: 3 },
  { t: "The fitness coach brought in a new sprint programme. The lads are flying. Form up for a few games.", who: "squad", f: 1, w: 2 },
  { t: "The fitness coach brought in a new sprint programme and overdid it. Dead legs everywhere. Form down.", who: "squad", f: -1, w: 1 },
  { t: "{p} tweaked a muscle in the warm up and is playing through it. Form down for a match.", who: "one", f: -2, w: 1 },
  { t: "{p} has been on a new diet and dropped three kilos. He looks sharp. Form up.", who: "one", f: 1, w: 0 },
  { t: "{p} has been on a new diet and is miserable. No pasta, no joy. Morale down.", who: "one", m: -0.5, w: 2 },
  { t: "A sports psychologist did a session with the squad. {p} says it changed everything. Form up.", who: "few", f: 1, w: 3 },
  { t: "The club brought in a set piece coach. The first session was a revelation. Form up for the squad.", who: "squad", f: 1, w: 1 },
  { t: "{p} skipped a recovery session to go shopping. The staff are not happy. Form down.", who: "one", f: -1, m: -0.5, w: 1 },
  { t: "The new training ground gym opened. The lads have never lifted so much. Form up.", who: "squad", f: 1, w: 2 },
  { t: "{p} has been doing yoga at dawn and swears by it. Form up.", who: "one", f: 1, w: 3 },
  { t: "The groundsman cut the training pitch too short and {p} slipped all session. Form down for a match.", who: "one", f: -1, w: 1 },
  { t: "The gaffer ran a brutal double session in the rain. Bodies sore but minds sharp. Form up.", who: "squad", f: 1, w: 1 },
  { t: "The club cancelled a day off to review the last game. Grumbles everywhere. Morale down.", who: "squad", m: -0.3, w: 1 },
  { t: "Training was cancelled because of snow. The lads built a snowman shaped like the gaffer. Morale up.", who: "squad", m: 0.3, w: 1 },
  { t: "{p} has been training with the first team keeper coach for fun and loves it. Morale up.", who: "one", m: 0.5, w: 2 },
  { t: "{p} won every sprint test this week. He is in the shape of his life. Form up.", who: "one", f: 2, w: 2 },
  { t: "{p} finished last in every sprint test this week. The staff have had words. Form down.", who: "one", f: -1, w: 1 },
  { t: "A video analysis session showed {p} exactly where he keeps losing his man. He has fixed it. Form up.", who: "one", f: 1, w: 0 },

  // ---------- contracts and money ----------
  { t: "{p} signed a new contract and the club gave him a cake with his face on it. Morale way up.", who: "one", m: 1.5, w: 0 },
  { t: "{p} has rejected a new contract offer and the fans have noticed. Morale down.", who: "one", m: -1, w: 0 },
  { t: "{p} found out a team mate earns double what he does. He has not taken it well. Morale down.", who: "one", m: -1, w: 3 },
  { t: "The club paid a win bonus early. Everyone got a nice surprise in the bank. Morale up.", who: "squad", m: 0.4, w: 1 },
  { t: "The club is late paying bonuses. Lots of muttering in the canteen. Morale down.", who: "squad", m: -0.4, w: 2 },
  { t: "{p} got a boot deal with a big brand. Free boots for life. Morale up.", who: "one", m: 1, w: 0 },
  { t: "{p} lost a boot deal after a poor run. He is wearing a rival brand and sulking. Morale down.", who: "one", m: -0.5, w: 2 },
  { t: "{p} was fined for being late three times. He says the traffic is not his fault. Morale down.", who: "one", m: -0.5, w: 1 },
  { t: "The board gave the squad a bonus for the last win. Everyone is happy. Morale up.", who: "squad", m: 0.3, w: 1 },
  { t: "{p} is in a row with the club over image rights. Lawyers involved. Morale down.", who: "one", m: -1, w: 3 },
  { t: "{p} donated a week's wages to a local food bank and the whole town loved it. Morale up.", who: "one", m: 1, w: 2 },
  { t: "The club gave everyone a new car for the season. The car park looks like a showroom. Morale up.", who: "squad", m: 0.3, w: 1 },

  // ---------- transfer talk ----------
  { t: "{p} is being linked with a move to a bigger club and has gone off the boil. Form down.", who: "one", f: -1, m: -0.5, w: 2 },
  { t: "{p} was linked with a move and told the press he is going nowhere. The fans love him for it. Morale up.", who: "one", m: 1, w: 2 },
  { t: "A scout from a big club was spotted at training watching {p}. He played out of his skin. Form up.", who: "one", f: 1, w: 1 },
  { t: "{p}'s agent has been shopping him around behind the club's back. The gaffer found out. Morale down.", who: "one", m: -1, w: 3 },
  { t: "The club turned down a bid for {p} and told him he is the future. Morale up.", who: "one", m: 1, w: 2 },
  { t: "Rumours of a big signing in the same position have {p} and {q} looking over their shoulders. Form up.", who: "few", f: 1, w: 2 },
  { t: "Rumours of a big signing in the same position have {p} and {q} worried. Morale down.", who: "few", m: -0.5, w: 2 },
  { t: "{p} went public saying he wants to leave. The dressing room is cold on him. Morale down.", who: "one", m: -1.5, w: 0 },

  // ---------- health and small knocks ----------
  { t: "A cold went round the dressing room. {n} players are sniffing and sneezing. Form down for a match.", who: "few", f: -1, w: 1 },
  { t: "{p} has hay fever and the pitch was just cut. He could not see the ball. Form down for a match.", who: "one", f: -1, w: 1 },
  { t: "{p} had a wisdom tooth out and is on soup. Form down for a couple of games.", who: "one", f: -1, w: 2 },
  { t: "{p} got stung by a wasp at training and his hand is huge. Form down for a match.", who: "one", f: -1, w: 1 },
  { t: "A stomach bug swept the squad. {n} players spent the week near a toilet. Form down.", who: "few", f: -2, w: 1 },
  { t: "{p} had a full medical check and the doctors say he is in the best shape of his career. Form up.", who: "one", f: 1, w: 3 },
  { t: "{p} tried a cryotherapy chamber and came out a new man. Form up for a match.", who: "one", f: 1, w: 1 },
  { t: "{p} got a new pair of contact lenses and says the goal looks bigger. Form up.", who: "one", f: 1, w: 3 },
  { t: "{p} cannot shake a cough. He is playing but puffing. Form down.", who: "one", f: -1, w: 2 },
  { t: "The club doctor found {p} was dehydrated all week. Water bottles everywhere now. Form up.", who: "one", f: 1, w: 1 },
  { t: "{p} slept on a bad pillow and has a stiff neck. He cannot head a ball. Form down for a match.", who: "one", f: -1, w: 1 },
  { t: "{p} had a massage therapist in from abroad and feels ten years younger. Form up.", who: "one", f: 1, w: 2 },

  // ---------- weather and grounds ----------
  { t: "A heatwave hit training all week. {n} players are wilting. Form down for the match.", who: "few", f: -1, w: 1 },
  { t: "A cold snap froze the training pitches. The squad trained indoors on a tiny court and loved it. Morale up.", who: "squad", m: 0.3, w: 1 },
  { t: "The stadium lights failed during a night session. The lads played a game of hide and seek. Morale up.", who: "squad", m: 0.2, w: 1 },
  { t: "The club put in a new pitch and it plays like a carpet. Form up for the squad at home.", who: "squad", f: 1, w: 2 },
  { t: "The roof of the dressing room leaked and {p}'s kit got soaked. He played in a spare. Form down for a match.", who: "one", f: -1, w: 1 },
  { t: "Fog cancelled training and the squad went to the cinema together. Morale up.", who: "squad", m: 0.3, w: 1 },
  { t: "The sprinklers came on during a tactics talk. Everyone got drenched and the gaffer laughed first. Morale up.", who: "squad", m: 0.3, w: 1 },
  { t: "A storm knocked the power out at the training ground. Cold showers all week. Form down.", who: "squad", f: -1, w: 1 },

  // ---------- form and confidence ----------
  { t: "{p} scored a worldie in a training game and has not stopped talking about it. Form up.", who: "one", f: 1, w: 2 },
  { t: "{p} missed three open goals in training and is in his own head. Form down.", who: "one", f: -1, w: 2 },
  { t: "The gaffer told {p} he is the first name on the team sheet. He is walking on air. Form up.", who: "one", f: 1, m: 1, w: 3 },
  { t: "The gaffer told {p} he needs to do more. He took it well and has been superb. Form up.", who: "one", f: 2, w: 2 },
  { t: "The gaffer told {p} he needs to do more. He took it badly. Form down.", who: "one", f: -1, m: -1, w: 2 },
  { t: "{p} got man of the match in a training game judged by the kit man. Nobody argued. Form up.", who: "one", f: 1, w: 1 },
  { t: "{p} has lost his place in the pecking order for penalties. He is sulking. Morale down.", who: "one", m: -0.5, w: 2 },
  { t: "{p} has been handed the penalties. He has been practising all week. Form up.", who: "one", f: 1, m: 0.5, w: 2 },
  { t: "The keeper saved four penalties in training. He is unbeatable this week. Form up.", who: "gk", f: 2, w: 1 },
  { t: "The keeper let three in from the halfway line in training. Everyone is a bit worried. Form down.", who: "gk", f: -2, w: 1 },
  { t: "The keeper got a new pair of gloves from his idol. He is sticking to everything. Form up.", who: "gk", f: 1, m: 0.5, w: 2 },
  { t: "The keeper was dropped from his national squad. Morale down.", who: "gk", m: -1, w: 3 },
  { t: "The keeper got called up by his country for the first time. Morale way up.", who: "gk", m: 1.5, w: 0 },
  { t: "{p} got his first call up for his country. The whole squad clapped him in. Morale up.", who: "one", m: 1.5, w: 0 },
  { t: "{p} was dropped from his national squad. He is taking it out on the training cones. Form down.", who: "one", f: -1, m: -1, w: 2 },
  { t: "{p} came back from international duty with a winner's medal. Form up.", who: "one", f: 1, m: 1, w: 2 },
  { t: "{p} came back from international duty having played three games in a week. Shattered. Form down.", who: "one", f: -1, w: 1 },
  { t: "{p} was named in the league team of the week. Form up.", who: "one", f: 1, w: 1 },
  { t: "{p} got an award from his old school. He gave a speech and everything. Morale up.", who: "one", m: 0.5, w: 1 },
  { t: "{p} has gone twelve games without a goal in training. He is pressing too hard. Form down.", who: "one", f: -1, w: 2 },

  // ---------- odd and fun ----------
  { t: "{p} got stuck in a lift for two hours with the kit man. They are now best friends. Morale up.", who: "one", m: 0.5, w: 1 },
  { t: "A seagull stole {p}'s lunch on the training ground. The video has a million views. Morale up all round.", who: "squad", m: 0.2, w: 1 },
  { t: "{p} locked his keys in his car and had to get a taxi to the game. He arrived flustered. Form down for a match.", who: "one", f: -1, w: 1 },
  { t: "{p} won the squad fantasy league and will not stop talking about it. Morale up.", who: "one", m: 0.5, w: 2 },
  { t: "{p} lost the squad fantasy league and has to wear a dress to training. The lads are howling. Morale up.", who: "squad", m: 0.3, w: 1 },
  { t: "{p} adopted a stray cat that lives at the training ground. The squad calls it the gaffer. Morale up.", who: "squad", m: 0.3, w: 2 },
  { t: "{p} got a terrible haircut and refuses to take his hat off. Form down for a match.", who: "one", f: -1, w: 1 },
  { t: "{p} dyed his hair the club colours for a bet. The fans are obsessed. Morale up.", who: "one", m: 1, w: 2 },
  { t: "The squad went bowling and {p} bowled a perfect game. Nobody can believe it. Morale up.", who: "squad", m: 0.3, w: 1 },
  { t: "The squad went to an escape room and got stuck for two hours. {p} blamed everyone. Morale down a touch.", who: "squad", m: -0.2, w: 1 },
  { t: "{p} fell asleep in a team meeting and snored. The gaffer let it slide. Everyone else laughed. Morale up.", who: "squad", m: 0.2, w: 1 },
  { t: "{p} appeared on a cooking show and burned everything. The squad watched it together. Morale up.", who: "squad", m: 0.3, w: 1 },
  { t: "{p} did a charity skydive. He cried the whole way down. The squad respects it. Morale up.", who: "one", m: 1, w: 2 },
  { t: "{p} got a tattoo of the club badge. Big commitment. The fans are thrilled. Morale up.", who: "one", m: 1, w: 3 },
  { t: "{p} got a tattoo of the wrong club badge by mistake. He is not talking about it. Morale down.", who: "one", m: -0.5, w: 1 },
  { t: "The club cat walked across the pitch during training and everyone stopped to watch. Nothing changed, nice moment.", who: "squad", m: 0.1, w: 1 },
  { t: "{p} swapped shirts with his childhood hero in a friendly and framed it. Morale up.", who: "one", m: 1, w: 2 },
  { t: "{p} won a game of chess against the gaffer. The gaffer wants a rematch. Morale up.", who: "one", m: 0.5, w: 1 },
  { t: "{p} got a parking ticket at the stadium on match day. He is fuming. Morale down for a match.", who: "one", m: -0.3, w: 1 },
  { t: "{p} found out he has a long lost cousin in the opposition squad. They swapped numbers. Nice story, no effect.", who: "one", w: 1 },
  { t: "A local school named their football pitch after {p}. He opened it in person. Morale up.", who: "one", m: 1, w: 2 },
  { t: "{p} got a speeding fine driving to training. He says he was late because of the dog. Morale down.", who: "one", m: -0.5, w: 1 },
  { t: "{p} has learned the local language and gave his first interview in it. The fans loved it. Morale up.", who: "one", m: 1, w: 3 },
  { t: "{p} got lost on his first drive to a new training ground and ended up in the next town. Form down for a match.", who: "one", f: -1, w: 1 },
  { t: "{p} and {q} started a podcast. It is mostly about biscuits. The squad loves it. Morale up.", who: "few", m: 0.5, w: 2 },
  { t: "{p} was pictured eating a kebab at 2am. The club had a word. Form down for a match.", who: "one", f: -1, m: -0.5, w: 1 },
  { t: "The squad found an old photo of the gaffer with a mullet. It is now the dressing room wallpaper. Morale up.", who: "squad", m: 0.3, w: 1 },
  { t: "{p} rescued a dog from a river on his day off. Local hero. Morale up.", who: "one", m: 1, w: 2 },
  { t: "{p} tried to cook for the squad and set off every alarm in the building. Morale up anyway.", who: "squad", m: 0.2, w: 1 },
  { t: "{p} got invited to a film premiere and walked the red carpet. He is insufferable now. Morale up.", who: "one", m: 0.5, w: 1 },

  // ---------- the club ----------
  { t: "The club chairman visited training and shook every hand. Nice touch. Morale up.", who: "squad", m: 0.3, w: 1 },
  { t: "The club chairman visited training and read out a list of what is wrong. Morale down.", who: "squad", m: -0.4, w: 1 },
  { t: "The club announced a new stadium plan. The squad is excited about the future. Morale up.", who: "squad", m: 0.4, w: 2 },
  { t: "The club announced cuts to the canteen. No more free toast. Mutiny brewing. Morale down.", who: "squad", m: -0.4, w: 2 },
  { t: "The club brought back free toast. Order is restored. Morale up.", who: "squad", m: 0.4, w: 1 },
  { t: "A club legend came in to speak to the squad. {p} could not stop smiling. Form up.", who: "squad", f: 1, w: 1 },
  { t: "The club launched a new kit and it is a beauty. Everyone wants to play in it. Morale up.", who: "squad", m: 0.3, w: 1 },
  { t: "The club launched a new kit and it is hideous. {p} says he looks like a deckchair. Morale down a touch.", who: "squad", m: -0.2, w: 1 },
  { t: "The club announced a tour of Asia for the summer. Half the squad is thrilled, half is already tired. No effect.", who: "squad", w: 1 },
  { t: "The club's kit man retired after thirty years. Big emotional goodbye. Morale up for the week.", who: "squad", m: 0.3, w: 1 },
  { t: "The club got a new team bus with massage seats. Travel will never be the same. Form up for the next trip.", who: "squad", f: 1, w: 1 },
  { t: "The club got a sponsorship from a local bakery. Free pastries every morning. Form down, morale up.", who: "squad", f: -1, m: 0.5, w: 1 },
  { t: "The club put {p} on the cover of the match day programme. He bought fifty copies for his family. Morale up.", who: "one", m: 0.5, w: 1 },
  { t: "The club's new nutritionist banned sauce. The squad is in mourning. Morale down.", who: "squad", m: -0.3, w: 2 },
  { t: "The club's new nutritionist is a genius and everyone has more energy. Form up.", who: "squad", f: 1, w: 2 },

  // ---------- rivals and the league ----------
  { t: "A rival club's player mocked {p} on social media before the game. He is out for revenge. Form up.", who: "one", f: 2, w: 1 },
  { t: "The squad watched the rivals lose on the telly together. Big cheers. Morale up.", who: "squad", m: 0.3, w: 1 },
  { t: "The rivals won a trophy and paraded it past the training ground. Salt in the wound. Morale down.", who: "squad", m: -0.3, w: 1 },
  { t: "{p} was asked which rival player he would sign and gave an honest answer. The fans are not happy. Morale down.", who: "one", m: -0.5, w: 1 },
  { t: "The league named {p} in its young player shortlist. Form up.", who: "one", f: 1, m: 0.5, w: 2 },
  { t: "A former team mate at a rival club told the press {p} was lazy. {p} is running twice as hard. Form up.", who: "one", f: 2, w: 2 },
  { t: "The referee's association apologised to the club for a bad decision last week. The squad feels vindicated. Morale up.", who: "squad", m: 0.3, w: 1 },
  { t: "A manager at another club called the squad soft in an interview. The lads are raging. Form up.", who: "squad", f: 1, w: 1 },

  // ---------- gaffer and staff ----------
  { t: "The gaffer took the squad out for pizza after a good week of training. Morale up.", who: "squad", m: 0.3, w: 1 },
  { t: "The gaffer threw a water bottle across the dressing room after training. Nobody is smiling. Morale down.", who: "squad", m: -0.4, w: 1 },
  { t: "The gaffer praised {p} in front of the whole squad. He has grown a foot. Form up.", who: "one", f: 1, m: 1, w: 2 },
  { t: "The gaffer tore into {p} in front of the whole squad. He is shaken. Form down.", who: "one", f: -1, m: -1, w: 2 },
  { t: "The gaffer switched off his phone and took the squad hiking. Fresh air, clear heads. Form up.", who: "squad", f: 1, w: 1 },
  { t: "The physio's magic hands sorted out a knot in {p}'s back he has had for a year. Form up.", who: "one", f: 1, w: 3 },
  { t: "The club's analyst found a weakness in the next opponent and the squad is buzzing to use it. Form up.", who: "squad", f: 1, w: 1 },
  { t: "The gaffer forgot {p}'s name in a press conference. The lads will not let it go. Morale up for everyone but him.", who: "one", m: -0.3, w: 1 },
  { t: "The gaffer gave the squad three days off out of the blue. Everyone came back refreshed. Form up.", who: "squad", f: 1, w: 1 },
  { t: "The gaffer cancelled days off until further notice. Grim faces. Morale down.", who: "squad", m: -0.4, w: 1 },
  { t: "The goalkeeping coach brought in a crossing machine that never misses. The keeper has been peppered all week. Form up.", who: "gk", f: 1, w: 2 },
  { t: "The keeper and the keeper coach had a loud row about positioning. Morale down.", who: "gk", m: -1, w: 2 },
  { t: "The keeper has been working on his kicking with a rugby coach. It is paying off. Form up.", who: "gk", f: 1, w: 3 },
  { t: "The keeper left his gloves at home and played in a pair from the club shop. Form down for a match.", who: "gk", f: -1, w: 1 },
  { t: "The keeper gave a motivational talk to the academy kids and came back inspired. Morale up.", who: "gk", m: 1, w: 2 },
  { t: "The keeper has a new superstition and must touch both posts before kick off. Nobody minds. No effect.", who: "gk", w: 1 },
  { t: "The keeper has been sleeping badly since the baby came. Form down for a few games.", who: "gk", f: -1, w: 3 },
  { t: "The keeper was voted best in the league by his fellow pros. Morale up.", who: "gk", m: 1, f: 1, w: 2 },
  { t: "The club bought a new scoreboard and the keeper keeps checking the clock. Form down for a match.", who: "gk", f: -1, w: 1 },
  { t: "The keeper wrote a children's book about a brave goalkeeper. It sold out locally. Morale up.", who: "gk", m: 1, w: 2 },

  // ---------- off the pitch injuries: kitchen, stairs, dogs, gym, DIY and the rest of real life ----------
  { h: "Kitchen chaos", t: "{p} tried to flip a pancake like a TV chef and caught the hot pan instead. Burned hand, out for {d}.", who: "one", inj: 1 },
  { h: "Onion trouble", t: "{p} was chopping onions with his eyes shut because they made him cry. He nicked his finger badly and needs stitches. Out for {d}.", who: "one", inj: 1 },
  { h: "Slippery stairs", t: "{p} went down the stairs in his socks, took the last four steps on his backside and twisted an ankle. Out for {d}.", who: "one", inj: [2, 3] },
  { h: "Walkies gone wrong", t: "{p}'s dog spotted a squirrel and took off. {p} kept hold of the lead and went face first into a hedge. Sore shoulder, out for {d}.", who: "one", inj: [1, 2] },
  { h: "Gym show off", t: "{p} tried to bench press more than the strength coach to win a bet. He did not win. Pulled chest muscle, out for {d}.", who: "one", inj: [2, 3] },
  { h: "DIY disaster", t: "{p} decided to put up shelves himself to save a few quid. He hit his thumb with the hammer and then dropped the shelf on his foot. Out for {d}.", who: "one", inj: [2, 3] },
  { h: "Toe meets bed", t: "{p} stubbed his little toe on the bed frame at 2am looking for the light switch. It is broken. Out for {d}.", who: "one", inj: [2, 3] },
  { h: "Trampoline trouble", t: "{p} joined his kids on the garden trampoline, went for a backflip and landed on his neck. Stiff as a board, out for {d}.", who: "one", inj: [1, 2] },
  { h: "Lego ambush", t: "{p} stepped on a Lego brick in the dark, hopped away in agony and crashed into the wardrobe. Bruised ribs, out for {d}.", who: "one", inj: 1 },
  { h: "Bike bother", t: "{p} rode his new electric bike to training, hit a kerb and went over the handlebars. Grazes everywhere and a sore knee. Out for {d}.", who: "one", inj: [2, 3] },
  { h: "Paddleboard plunge", t: "{p} tried paddleboarding on his day off, fell in, and twisted his knee climbing back on. Out for {d}.", who: "one", inj: [2, 4] },
  { h: "Bathroom slip", t: "{p} slipped on a wet bathroom floor and caught the edge of the bath with his hip. Badly bruised, out for {d}.", who: "one", inj: 1 },
  { h: "Garden war", t: "{p} lost a fight with a rose bush while doing the garden. Thorns in both hands and a nasty cut that got infected. Out for {d}.", who: "one", inj: 1 },
  { h: "Wrong ladder", t: "{p} climbed a wobbly ladder to clear the gutters. The ladder won. Sprained wrist and a sore back, out for {d}.", who: "one", inj: [2, 3] },
  { h: "Sofa lift", t: "{p} helped his brother carry a sofa up three flights of stairs. His back has not forgiven him. Out for {d}.", who: "one", inj: [1, 2] },
  { h: "Toast burn", t: "{p} tried to fish a stuck slice of toast out of the toaster with a fork. Small shock, big fright, burned fingers. Out for {d}.", who: "one", inj: 1 },
  { h: "Ice rink fall", t: "{p} took his family ice skating, went full speed to impress the kids and spun into the barrier. Sore shoulder, out for {d}.", who: "one", inj: [2, 3] },
  { h: "Dog tangle", t: "{p} was walking three dogs for a neighbour when all three went different ways round a lamp post. Twisted knee, out for {d}.", who: "one", inj: [2, 3] },
  { h: "Car door", t: "{p} shut his own hand in the car door while juggling shopping bags. Two swollen fingers, out for {d}.", who: "one", inj: 1 },
  { h: "Pool party", t: "{p} dived into the shallow end at a family pool party. Bumped head and a sore neck. The doctor says rest for {d}.", who: "one", inj: [1, 2] },
  { h: "Beach football", t: "{p} played beach football with his cousins on holiday and rolled his ankle in a sand hole. Out for {d}.", who: "one", inj: [2, 3] },
  { h: "Snowball fight", t: "{p} went all in on a snowball fight with the neighbours' kids, slipped on ice and landed on his wrist. Out for {d}.", who: "one", inj: [1, 2] },
  { h: "Cat scratch", t: "{p}'s cat did not want a bath. {p} has deep scratches up both arms and one got infected. Out for {d}.", who: "one", inj: 1 },
  { h: "Fridge drop", t: "{p} tried to move the fridge to find the remote. The fridge moved onto his foot. Out for {d}.", who: "one", inj: [2, 3] },
  { h: "Yoga stretch", t: "{p} went to his first hot yoga class and stretched something he did not know he had. Pulled groin, out for {d}.", who: "one", inj: [2, 3] },
  { h: "Fancy dress fall", t: "{p} went to a party dressed as a giant banana, could not see his feet and fell off the patio. Sprained ankle, out for {d}.", who: "one", inj: [2, 3] },
  { h: "Hot coffee", t: "{p} spilled a full pot of coffee in his lap during breakfast. Nasty burn, he cannot run properly for {d}.", who: "one", inj: 1 },
  { h: "Spin class", t: "{p} went to a spin class, kept up with the instructor for an hour and pulled his hamstring getting off the bike. Out for {d}.", who: "one", inj: [2, 4] },
  { h: "Wardrobe flat pack", t: "{p} spent six hours building a flat pack wardrobe. It fell on him at the last step. Bruised back, out for {d}.", who: "one", inj: [1, 2] },
  { h: "Football with the kids", t: "{p} played in goal for his son's birthday party, dived for a shot from a seven year old and landed on a toy truck. Cracked rib, out for {d}.", who: "one", inj: [3, 4] },
  { h: "Squash rivalry", t: "{p} lost a squash match to his agent and got so angry he ran into the wall. Sore shoulder, out for {d}.", who: "one", inj: [1, 2] },
  { h: "Golf buggy", t: "{p} drove a golf buggy too fast down a hill on his day off. It tipped over gently but his knee did not enjoy it. Out for {d}.", who: "one", inj: [2, 3] },
  { h: "Hammock flip", t: "{p} got into a garden hammock the wrong way and it flipped him straight onto the patio. Sore back, out for {d}.", who: "one", inj: 1 },
  { h: "Shopping trolley", t: "{p} rode a shopping trolley down the car park ramp to make his kids laugh. They laughed. He sprained his wrist. Out for {d}.", who: "one", inj: [1, 2] },
  { h: "Barbecue burn", t: "{p} lit the barbecue with far too much lighter fluid. No eyebrows and a burned hand. Out for {d}.", who: "one", inj: 1 },
  { h: "Escalator trip", t: "{p} was on his phone on the shopping centre escalator and missed the last step. Twisted ankle, out for {d}.", who: "one", inj: [1, 2] },
  { h: "Bunk bed bump", t: "{p} sat up too fast in his kid's bunk bed during a sleepover and smacked his head on the ceiling. Mild concussion, out for {d}.", who: "one", inj: [1, 2] },
  { h: "Rowing machine", t: "{p} tried to beat his own record on the rowing machine at home and tweaked his lower back. Out for {d}.", who: "one", inj: [1, 2] },
  { h: "Window cleaning", t: "{p} leaned too far out of an upstairs window to clean it and pulled a muscle in his side. Out for {d}.", who: "one", inj: [1, 2] },
  { h: "Dog park sprint", t: "{p} raced his greyhound across the dog park to show off. The greyhound won and {p} pulled his calf. Out for {d}.", who: "one", inj: [2, 3] },
  { h: "Tile trouble", t: "{p} tried to tile his own bathroom and knelt on a broken tile for an afternoon. Cut knee, out for {d}.", who: "one", inj: 1 },
  { h: "Massage chair", t: "{p} fell asleep in a shop massage chair on the strongest setting for an hour. His back is in knots. Out for {d}.", who: "one", inj: 1 },
  { h: "Skateboard dad", t: "{p} borrowed his nephew's skateboard to show him how it is done. It was not done. Sprained wrist, out for {d}.", who: "one", inj: [2, 3] },
  { h: "Garage door", t: "{p} ducked under the garage door as it came down and did not duck far enough. Bump on the head, out for {d}.", who: "one", inj: 1 },
  { h: "Wedding dance", t: "{p} went wild on the dance floor at his cousin's wedding and did the worm. His shoulder popped out. Out for {d}.", who: "one", inj: [3, 4] },
  { h: "Ladder at the shop", t: "{p} reached for a high shelf in a DIY shop, slipped off the step and landed on his tailbone. Out for {d}.", who: "one", inj: [1, 2] },
  { h: "Hot water bottle", t: "{p}'s hot water bottle burst in bed. He has a scald on his thigh and cannot run for {d}.", who: "one", inj: 1 },
  { h: "Spicy challenge", t: "{p} took on the hottest chicken wing challenge in town. He finished it. His stomach did not recover in time. Out for {d}.", who: "one", inj: 1 },
  { h: "Rock climbing", t: "{p} went indoor rock climbing with mates and let go at the top before the rope was ready. Twisted ankle on landing, out for {d}.", who: "one", inj: [2, 3] },
  { h: "Paintball welt", t: "{p} took a paintball shot right on the kneecap from close range at a stag do. Swollen knee, out for {d}.", who: "one", inj: 1 },
  { h: "Bouncy castle", t: "{p} went on the bouncy castle at his daughter's party and collided with the uncle who also went on it. Both have black eyes. Out for {d}.", who: "one", inj: 1 },
  { h: "Wheelbarrow", t: "{p} helped his dad move a pile of logs with a wheelbarrow and tipped the lot onto his own shin. Out for {d}.", who: "one", inj: [1, 2] },
  { h: "Late night snack", t: "{p} went for a midnight snack, opened a cupboard door into his own forehead in the dark and needed a stitch. Out for {d}.", who: "one", inj: 1 },
  { h: "Horse riding", t: "{p} went horse riding on holiday and the horse decided the ride was over. He landed on his side. Out for {d}.", who: "one", inj: [3, 5] },
  { h: "Glass door", t: "{p} walked straight into a very clean glass door at a fancy restaurant. Broken nose, out for {d} while it settles.", who: "one", inj: [1, 2] },
  { h: "Tumble dryer", t: "{p} climbed on the tumble dryer to reach the top cupboard. It was running. Bruised knee and a dent in the dryer. Out for {d}.", who: "one", inj: 1 },
  { h: "Sledge race", t: "{p} raced his brother down a snowy hill on tea trays and hit a tree stump. Bruised hip, out for {d}.", who: "one", inj: [1, 2] },
  { h: "Keeper DIY", t: "The keeper hung a new mirror at home, missed the nail with the hammer and hit his own glove hand. Swollen fingers, out for {d}.", who: "gk", inj: [1, 2] },
  { h: "Keeper and the dog", t: "The keeper's big dog jumped up to say hello and landed on his foot. Two toes are sprained. Out for {d}.", who: "gk", inj: 1 },
  { h: "Keeper gym slip", t: "The keeper dropped a dumbbell on his toe showing a fan how heavy his weights are. Out for {d}.", who: "gk", inj: [1, 2] },
  // ---------- home and family, round two ----------
  { h: "Twins!", t: "{p} found out he is having twins. He has not stopped grinning or doing sums about nappies. Morale way up.", who: "one", m: 1.5, w: 0 },
  { h: "Mum moves in", t: "{p}'s mum has moved in for a month to help out. The fridge has never been fuller. Form up for a few games.", who: "one", f: 1, w: 3 },
  { h: "Noisy neighbours", t: "{p}'s new neighbours are learning the drums. Every night. Until midnight. Form down for a couple of games.", who: "one", f: -1, w: 2 },
  { h: "House flood", t: "A pipe burst at {p}'s house while he was away. He spent three days with buckets and a mop. Form and morale down.", who: "one", f: -1, m: -0.5, w: 2 },
  { h: "School play", t: "{p} skipped a day of rest to watch his daughter play a tree in the school play. Best tree he has ever seen. Morale up.", who: "one", m: 1, w: 2 },
  { h: "Sleepless nights", t: "{p}'s toddler has decided that 4am is the best time to play. Form down for a few games.", who: "one", f: -1, w: 3 },
  { h: "Family wedding", t: "{p} was best man at his brother's wedding. The speech got a standing ovation. He is on cloud nine.", who: "one", m: 1, w: 0 },
  { h: "Lost the ring", t: "{p} lost his wedding ring down a drain and spent a day with a torch and a coat hanger. He did not find it. Morale down.", who: "one", m: -0.5, w: 2 },
  { h: "Broken boiler", t: "{p}'s boiler packed in during a cold snap and he has been showering at the training ground. Morale down a touch.", who: "one", m: -0.5, w: 2 },
  { h: "Old school reunion", t: "{p} went to his school reunion and everyone wanted a selfie. Even the PE teacher who dropped him. Morale up.", who: "one", m: 1, w: 2 },
  { h: "Driving ban", t: "{p} lost his licence for speeding and now gets a lift from his nan. The lads have noticed. Morale down.", who: "one", m: -1, w: 3 },
  { h: "New house", t: "{p} got the keys to his dream house this week. Big garden, big smile. Morale up.", who: "one", m: 1, w: 0 },
  { h: "Pet goldfish", t: "{p}'s goldfish Steve died after eleven years. He is taking it harder than anyone expected. Morale down for a bit.", who: "one", m: -0.5, w: 2 },
  { h: "Proud dad", t: "{p}'s son scored his first ever goal for the under eights. {p} cried in the car park. Morale up.", who: "one", m: 1, w: 2 },
  { h: "Wrong flight home", t: "{p} booked his family's holiday flights for the wrong month. His wife is not speaking to him. Morale down.", who: "one", m: -1, w: 2 },
  { h: "Lottery syndicate", t: "The squad's lottery syndicate won forty pounds. They split it into lots of tiny bits and still celebrated. Morale up.", who: "squad", m: 0.3, w: 1 },
  { h: "Grandad's birthday", t: "{p} flew home to see his grandad turn one hundred. A long trip, but worth every minute. Morale up, legs a bit heavy.", who: "one", m: 1, f: -1, w: 1 },
  { h: "House hunt", t: "{p} has spent every free hour looking at houses. He has seen forty. He liked none. Form down a touch.", who: "one", f: -1, w: 2 },
  { h: "Big family meal", t: "{p} cooked a huge Sunday roast for twenty relatives and nobody got food poisoning. He is very proud. Morale up.", who: "one", m: 0.5, w: 1 },
  { h: "Kids' sports day", t: "{p} came last in the dads' race at sports day. The video is everywhere. The lads cannot stop laughing, he can.", who: "one", m: -0.5, w: 1 },
  { h: "Burglary", t: "{p}'s house was broken into while he was at an away game. Nobody was hurt but he is shaken. Form and morale down.", who: "one", f: -1, m: -1, w: 3 },
  { h: "Teething", t: "{p}'s baby is teething and the whole house is awake every night. Form down for a few games.", who: "one", f: -1, w: 3 },
  { h: "Long distance", t: "{p}'s girlfriend got a job abroad. They are trying long distance and he is on video calls until 1am. Form down.", who: "one", f: -1, w: 2 },
  { h: "Family reunited", t: "{p}'s family finally got their visas and moved over to join him. Home feels like home now. Form and morale up.", who: "one", f: 1, m: 1, w: 0 },
  { h: "Cooking class", t: "{p} has been taking cooking classes and brought a lemon cake in for the squad. Morale up for everyone.", who: "squad", m: 0.3, w: 1 },
  { h: "Garden gnome", t: "Someone stole {p}'s prize garden gnome and is posting photos of it around the world. He finds it funny. Morale up.", who: "one", m: 0.5, w: 1 },
  { h: "The in laws", t: "{p}'s in laws are staying for two weeks and they have opinions about everything, including his first touch. Morale down.", who: "one", m: -0.5, w: 2 },
  { h: "Charity run", t: "{p} ran a charity 10k with his mum on a rest day. Raised loads, legs like jelly. Morale up, form down a touch.", who: "one", m: 1, f: -1, w: 1 },
  { h: "Spelling bee", t: "{p}'s daughter won the regional spelling bee. He has told every single person at the club. Morale up.", who: "one", m: 1, w: 2 },
  { h: "Power cut", t: "A power cut hit the whole street the night before the game. {p} slept badly in the cold. Form down for a match.", who: "one", f: -1, w: 1 },

  // ---------- the training ground ----------
  { h: "Crossbar challenge", t: "{p} hit the crossbar ten times in a row from the edge of the box. The lads lifted him onto their shoulders. Form up.", who: "one", f: 1, w: 2 },
  { h: "Muddy pitches", t: "The training pitches are a bog after a week of rain. Nobody can pass the ball more than five yards. Form down.", who: "squad", f: -1, w: 1 },
  { h: "New pitch", t: "The training ground got a brand new pitch, smooth as a snooker table. Sharp sessions all week. Form up.", who: "squad", f: 1, w: 2 },
  { h: "Rondo king", t: "{p} went a whole week without losing the ball in the rondo. The coaches are talking about him. Form up.", who: "one", f: 1, w: 2 },
  { h: "Shooting slump", t: "{p} has not scored in training for two weeks and the lads have started a count on the whiteboard. Form down.", who: "one", f: -1, m: -0.5, w: 2 },
  { h: "Fitness test", t: "The squad did the dreaded beep test. {p} won it and has been unbearable ever since. Form up for him.", who: "one", f: 1, w: 2 },
  { h: "Double sessions", t: "The gaffer brought in double sessions all week. Fitter in the long run, dead legs right now. Form down for a match.", who: "squad", f: -1, w: 1 },
  { h: "Set piece secret", t: "The coaches cooked up a new corner routine and the lads love it. Spirits high for the next game. Form up.", who: "squad", f: 1, w: 1 },
  { h: "Wrong kit day", t: "{p} turned up to training in the old kit and had to do it in his pants and a bib. The lads loved it, he did not.", who: "one", m: -0.5, w: 1 },
  { h: "Youth team embarrass", t: "The academy kids beat the first team in a training game. Nobody is talking about it. Morale down.", who: "squad", m: -0.4, w: 1 },
  { h: "Goose on the loose", t: "A goose has taken over the training ground and chases anyone who goes near the corner flag. The squad named it Gary. Morale up.", who: "squad", m: 0.4, w: 2 },
  { h: "Video session", t: "The analyst showed {p} a ten minute clip of every mistake he made last month. Useful, but brutal. Morale down, form up.", who: "one", m: -0.5, f: 1, w: 2 },
  { h: "Weak foot work", t: "{p} spends his evenings kicking a ball at his garage door with his weaker foot. The neighbours hate it, the coaches love it. Form up.", who: "one", f: 1, w: 3 },
  { h: "Pre season flashback", t: "The fitness coach made the squad run up the big hill again. Two players were sick. Form down for a match.", who: "squad", f: -1, w: 1 },
  { h: "Kit man DJ", t: "The kit man took over the dressing room speaker and played nothing but old love songs all week. The lads pretend to hate it. Morale up.", who: "squad", m: 0.3, w: 1 },
  { h: "Nutmeg of the week", t: "{p} nutmegged the captain three times in one drill. The video went round the dressing room. Morale up for him.", who: "one", m: 1, w: 2 },
  { h: "Shooting machine", t: "The club bought a ball machine that fires shots at 70 miles an hour. Strikers and keepers both love it. Form up.", who: "few", f: 1, w: 2 },
  { h: "Heavy legs", t: "The GPS data says {n} players have been running too much in training. The sports scientist wants them to ease off. Form down.", who: "few", f: -1, w: 1 },
  { h: "Language lessons", t: "{p} has been taking language lessons and finally understood the gaffer's team talk. Form up.", who: "one", f: 1, w: 3 },
  { h: "Cold baths", t: "The new recovery coach made everyone sit in ice baths. Teeth chattering, legs feeling brand new. Form up.", who: "squad", f: 1, w: 1 },
  { h: "Mystery stomach bug", t: "A bug went round the training ground and {n} players spent the week feeling rough. Form down for a game.", who: "few", f: -1, w: 1 },
  { h: "Tactics board", t: "The gaffer drew the new tactic on the board for an hour. {p} still does not understand it. Form down.", who: "one", f: -1, w: 2 },
  { h: "Penalty shoot out drill", t: "The squad finished training with a penalty shoot out for who buys coffee. {p} lost and paid for thirty lattes. Morale down for him.", who: "one", m: -0.5, w: 1 },
  { h: "Great week", t: "Every drill clicked this week. The passing was sharp and the shooting was sharper. Form up for the squad.", who: "squad", f: 1, w: 1 },
  { h: "Coach's birthday", t: "The squad surprised the fitness coach with a cake for his birthday and he let them off the running. Morale up.", who: "squad", m: 0.3, w: 1 },
  { h: "Fog day", t: "Thick fog meant training was cancelled and the squad played table tennis all morning. Not much work done, lots of fun.", who: "squad", m: 0.2, f: -1, w: 1 },
  { h: "Young star", t: "{p} has been the best player in training all week by a mile. The senior lads are asking where it came from. Form up.", who: "one", f: 2, w: 2 },
  { h: "Wrong boots", t: "{p} is trying out new boots from a new sponsor and keeps slipping. Form down until he gets used to them.", who: "one", f: -1, w: 2 },
  { h: "Head tennis", t: "{p} and {q} won the head tennis cup at training on a last gasp point. The trophy is a painted mug. Morale up.", who: "few", m: 0.5, w: 2 },
  { h: "Extra sessions", t: "{p} asked the coaches for extra work after training every day this week. It shows. Form up.", who: "one", f: 1, w: 2 },
  // ---------- fans and the town ----------
  { h: "Hospital visit", t: "The squad visited the children's hospital and handed out shirts. Nobody had a dry eye. Morale up for everyone.", who: "squad", m: 0.5, w: 2 },
  { h: "Fan mural", t: "Fans painted a giant mural of {p} on the side of a chip shop. He drove past it four times. Morale way up.", who: "one", m: 1.5, w: 0 },
  { h: "Booed in town", t: "{p} got booed by a group of fans in the supermarket after the last result. He left his trolley and went home. Morale down.", who: "one", m: -1, w: 2 },
  { h: "Fan of the week", t: "A 90 year old fan who has not missed a home game since 1950 came to meet the squad. Big hugs, big lift. Morale up.", who: "squad", m: 0.4, w: 2 },
  { h: "Banner blunder", t: "The fans made a huge banner for {p} but spelled his name wrong. He loves it anyway. Morale up.", who: "one", m: 0.5, w: 1 },
  { h: "Open training", t: "The club opened training to the fans and 5000 turned up in the rain to cheer every pass. Morale up for the squad.", who: "squad", m: 0.5, w: 1 },
  { h: "Lost the dog", t: "{p}'s dog ran off on a walk and the whole town went looking. A fan found him in a bakery. {p} cannot thank them enough. Morale up.", who: "one", m: 1, w: 2 },
  { h: "School visit", t: "{p} visited his old primary school and the kids asked him if he knew any famous footballers. Morale down, slightly.", who: "one", m: -0.3, w: 1 },
  { h: "Pub quiz", t: "The squad entered the local pub quiz in disguise and won. Then everyone recognised them anyway. Morale up.", who: "squad", m: 0.3, w: 1 },
  { h: "Chant of his own", t: "The fans came up with a new chant for {p}. It is very catchy and slightly rude. He loves it. Form up.", who: "one", f: 1, m: 0.5, w: 2 },
  { h: "Car park chat", t: "{p} spent an hour in the car park chatting to fans after training. They told him exactly how to play. Morale up.", who: "one", m: 0.5, w: 1 },
  { h: "Wrong shirt", t: "A fan got {p}'s name tattooed on his arm. It is spelled right but the photo is of someone else. Awkward. No real effect.", who: "one", m: 0.1, w: 1 },
  { h: "Season ticket record", t: "The club sold a record number of season tickets this week. The squad feels the town is right behind them. Morale up.", who: "squad", m: 0.4, w: 2 },
  { h: "Away end anger", t: "The away fans gave the squad a hard time on the walk to the bus after the last game. Morale down for the trip.", who: "squad", m: -0.4, w: 1 },
  { h: "Mascot mayhem", t: "The club mascot challenged {p} to a race at half time of a youth game. The mascot won. The lads have the video. Morale down for him.", who: "one", m: -0.5, w: 1 },

  // ---------- media and phones ----------
  { h: "Orange juggler", t: "A clip of {p} doing keepy ups with an orange in the canteen is all over the internet. He is walking taller. Morale up.", who: "one", m: 1, w: 2 },
  { h: "Old tweets", t: "Someone dug up {p}'s old posts from when he was fifteen. They are mostly about crisps but one was rude about the club. Morale down.", who: "one", m: -1, w: 2 },
  { h: "Podcast debut", t: "{p} went on a big football podcast and was the funniest guest they have ever had. Morale up.", who: "one", m: 1, w: 2 },
  { h: "Pundit pile on", t: "A TV pundit spent five minutes saying {p} is not good enough for this level. {p} watched it twice. Form up, he wants to prove him wrong.", who: "one", f: 1, m: -0.5, w: 2 },
  { h: "Phone stolen", t: "{p}'s phone was nicked at a petrol station and he has lost all his baby photos. Morale down.", who: "one", m: -1, w: 2 },
  { h: "Group chat leak", t: "The squad group chat got screenshotted and leaked. It was mostly memes about the physio. Squad morale down a touch.", who: "squad", m: -0.3, w: 1 },
  { h: "Documentary crew", t: "A camera crew is following the squad for a documentary. Some love it, some hate it. Form down a touch for the squad.", who: "squad", f: -1, m: 0.3, w: 1 },
  { h: "Magazine cover", t: "{p} is on the cover of a big fashion magazine this month. The lads have stuck it all over the dressing room. Morale up.", who: "one", m: 1, w: 2 },
  { h: "Transfer rumour", t: "A newspaper says a giant club wants {p}. Nobody has called. He keeps checking his phone anyway. Form down.", who: "one", f: -1, w: 2 },
  { h: "Gaming stream", t: "{p} streamed himself playing football games until 3am and lost to a twelve year old. Form down and very tired.", who: "one", f: -1, m: -0.3, w: 1 },
  { h: "Fake news", t: "A fake story said {p} wants to leave. He has spent the week saying he loves the club to anyone who will listen. Morale down.", who: "one", m: -0.5, w: 2 },
  { h: "Advert shoot", t: "{p} filmed an advert for a crisp company. Forty takes of biting a crisp. He never wants to see one again. Form down a touch.", who: "one", f: -1, w: 1 },
  { h: "Award night", t: "{p} won player of the month at a fancy awards night. Nice trophy, late night. Morale up.", who: "one", m: 1, f: 1, w: 2 },
  { h: "Quiz show", t: "{p} went on a TV quiz show for charity and won it. Turns out he knows every capital city. Morale up.", who: "one", m: 1, w: 2 },
  { h: "Interview gaffe", t: "{p} called the opponent the wrong name in his pre match interview. Twice. Morale down, a bit.", who: "one", m: -0.4, w: 1 },

  // ---------- money, cars and gadgets ----------
  { h: "Supercar regret", t: "{p} bought a supercar and it will not fit in the training ground car park. He has to park in the next street. Morale down.", who: "one", m: -0.5, w: 2 },
  { h: "New contract buzz", t: "{p}'s agent says talks about a new deal are going well. He is buzzing. Form up.", who: "one", f: 1, m: 0.5, w: 2 },
  { h: "Bad investment", t: "{p} put money into a friend's smoothie business and it closed after a week. Morale down.", who: "one", m: -1, w: 2 },
  { h: "Parking tickets", t: "{p} has collected six parking tickets in a week outside the training ground. The club has had a word. Morale down.", who: "one", m: -0.4, w: 1 },
  { h: "Bonus paid", t: "The win bonuses finally went into the bank this week. Lots of smiling faces in the dressing room. Morale up.", who: "squad", m: 0.3, w: 1 },
  { h: "Car crash scare", t: "{p} was in a small bump on the motorway. Nobody hurt but his car is a mess and he is rattled. Form down.", who: "one", f: -1, m: -0.5, w: 2 },
  { h: "Smart home", t: "{p}'s new smart home system keeps turning on the lights at 3am and playing jazz. Form down for a match.", who: "one", f: -1, w: 1 },
  { h: "Charity auction", t: "{p}'s signed boots went for a fortune at a charity auction. All the money goes to the local food bank. Morale up.", who: "one", m: 1, w: 2 },
  { h: "Sponsor gift", t: "The club sponsor gave every player a new massage gun. The dressing room sounds like a building site. Form up.", who: "squad", f: 1, w: 1 },
  { h: "Phone upgrade", t: "{p} spent the whole week setting up his new phone and missed his recovery session. Form down for a match.", who: "one", f: -1, w: 1 },

  // ---------- food and health ----------
  { h: "Chef's special", t: "The training ground chef made his famous curry and the whole squad went back for thirds. Morale up, form down a touch.", who: "squad", m: 0.4, f: -1, w: 1 },
  { h: "Sweet tooth", t: "{p} was caught with a secret stash of chocolate in his locker. The nutritionist cried. Form down.", who: "one", f: -1, w: 2 },
  { h: "Plant power", t: "{p} has gone vegan and says he has never felt better. He is flying in training. Form up.", who: "one", f: 1, w: 3 },
  { h: "Bad cold", t: "{p} has a stinking cold and has been sneezing on everyone. Form down for him for a couple of games.", who: "one", f: -1, w: 2 },
  { h: "Eye test", t: "{p} got his eyes tested and needs contact lenses. He says he can see the ball properly for the first time in years. Form up.", who: "one", f: 1, w: 0 },
  { h: "Sleep coach", t: "The club hired a sleep coach and everyone is getting nine hours. Form up across the squad.", who: "squad", f: 1, w: 2 },
  { h: "Takeaway night", t: "The squad ordered a giant takeaway the night before the game. The nutritionist is on holiday. Form down for the match.", who: "squad", f: -1, w: 1 },
  { h: "Hay fever", t: "Pollen season is here and {p} cannot stop sneezing. His eyes are like tomatoes. Form down for a few games.", who: "one", f: -1, w: 3 },
  { h: "Water challenge", t: "The squad did a drink more water challenge all week. Everyone feels sharp and has been to the toilet a lot. Form up.", who: "squad", f: 1, w: 1 },
  { h: "Dentist drama", t: "{p} had a filling and the numbness has not worn off. He is dribbling his water at training. Form down for a match.", who: "one", f: -1, w: 1 },

  // ---------- weather and the stadium ----------
  { h: "Early starts", t: "Building work next to the training ground starts at 7am, so sessions moved to the afternoon and the whole routine is off. Form down for a match.", who: "squad", f: -1, w: 1 },
  { h: "Snow day", t: "Snow covered the training ground and the squad had a snowball fight instead. Morale up, no harm done.", who: "squad", m: 0.4, w: 1 },
  { h: "Storm damage", t: "A storm ripped part of the roof off the main stand. The squad helped clear up. Morale up, legs a bit tired.", who: "squad", m: 0.3, f: -1, w: 1 },
  { h: "New floodlights", t: "The club put in brand new floodlights and the pitch looks like a TV studio. The lads cannot wait to play under them. Form up.", who: "squad", f: 1, w: 1 },
  { h: "Dressing room revamp", t: "The home dressing room got a full revamp with new benches, music and mood lighting. Morale up.", who: "squad", m: 0.5, w: 2 },
  { h: "Pigeons", t: "A family of pigeons moved into the dugout roof. The coaching staff are not happy. The players think it is hilarious. Morale up.", who: "squad", m: 0.2, w: 1 },
  { h: "Freezing showers", t: "The hot water in the dressing room broke for a week. Cold showers every day. Morale down.", who: "squad", m: -0.4, w: 1 },
  { h: "Pitch invader", t: "A pitch invader ran on in the last game and gave {p} a big hug. {p} thought it was nice. Morale up.", who: "one", m: 0.5, w: 1 },
  { h: "Fog on the motorway", t: "Thick fog slowed the bus home after the last game and the squad got back at 4am. Form down for the next match.", who: "squad", f: -1, w: 1 },
  { h: "Sunny days", t: "The sun came out all week and training was a joy. Shorts, sunglasses and big smiles. Morale up.", who: "squad", m: 0.3, w: 1 },

  // ---------- keepers, round two ----------
  { h: "Keeper's new gloves", t: "The keeper got gloves made just for his hands. He says the ball sticks to them like glue. Form up.", who: "gk", f: 1, w: 3 },
  { h: "Keeper laughs", t: "The keeper took part in a charity penalty shoot out against school kids and let in every one on purpose. Morale up.", who: "gk", m: 0.5, w: 1 },
  { h: "Keeper's worry", t: "The keeper made a howler in training and the video is doing the rounds. He has gone very quiet. Morale down.", who: "gk", m: -1, w: 2 },
  { h: "Keeper's eyes", t: "The keeper started eye training with a special light board. His reactions are lightning. Form up.", who: "gk", f: 1, w: 2 },
  { h: "Keeper's back", t: "The keeper slept on a hotel sofa bed and woke up stiff. He is diving like an old door. Form down for a match.", who: "gk", f: -1, w: 1 },
  { h: "Keeper hero", t: "The keeper saved a dog from a frozen pond on his day off. The local paper calls him a hero. Morale way up.", who: "gk", m: 1.5, w: 0 },
  { h: "Keeper's mind", t: "The keeper has started working with a sports psychologist. He is calmer than ever between the sticks. Form up.", who: "gk", f: 1, w: 0 },
  { h: "Keeper's rival", t: "The club signed a young keeper on trial and the number one is feeling the heat. He is training like a demon. Form up.", who: "gk", f: 1, m: -0.5, w: 2 },
  { h: "Keeper's game", t: "The keeper has been playing a goalkeeper video game every night to study angles. His wife is less impressed. Form up a touch.", who: "gk", f: 1, w: 1 },
  { h: "Keeper's hair", t: "The keeper dyed his hair bright green for charity. The lads have not stopped laughing. Morale up for the group.", who: "squad", m: 0.3, w: 1 },
  // ---------- the road and the rivals, round two ----------
  { h: "Hotel karaoke", t: "The team hotel had a karaoke night and {p} sang a power ballad that brought the house down. Morale up for everyone.", who: "squad", m: 0.4, w: 1 },
  { h: "Lost luggage", t: "{p}'s suitcase went to the wrong country. He has been in the same tracksuit for three days. Morale down.", who: "one", m: -0.5, w: 1 },
  { h: "Window seat war", t: "{p} and {q} had a proper row about the window seat on the plane. The gaffer had to step in. Morale down for both.", who: "few", m: -0.5, w: 1 },
  { h: "Bus quiz", t: "The bus trip turned into a three hour quiz with the kit man as host. Best journey of the season. Morale up.", who: "squad", m: 0.3, w: 1 },
  { h: "Sat nav fail", t: "The bus sat nav sent the squad down a farm track and they had to reverse for a mile. Arrived late and grumpy. Form down.", who: "squad", f: -1, w: 1 },
  { h: "Hotel spa", t: "The team hotel had a proper spa and the physios used every inch of it. Legs feel brand new. Form up.", who: "squad", f: 1, w: 1 },
  { h: "Rival mind games", t: "The next opponent's manager said the squad has no heart. It is on the dressing room wall now. Form up.", who: "squad", f: 1, w: 1 },
  { h: "Old club return", t: "{p} is up against his old club soon and their fans have been sending him messages all week. Form up, he wants this one.", who: "one", f: 1, m: -0.3, w: 1 },
  { h: "League fine", t: "The league fined the club for being late out of the tunnel last week. The gaffer has made everyone run for it. Morale down.", who: "squad", m: -0.3, w: 1 },
  { h: "International call up", t: "{p} got his first call up to the national squad. He rang his mum from the car park in tears. Morale way up.", who: "one", m: 1.5, f: 1, w: 0 },
  { h: "Prank call", t: "{p} got a call he thought was from the national team boss. It was the kit man doing a voice. Morale down for him, the dressing room loved it.", who: "one", m: -0.5, w: 1 },
  { h: "Bad hotel beds", t: "The hotel beds were as hard as a park bench. The whole squad slept badly. Form down for the match.", who: "squad", f: -1, w: 1 },
  { h: "Delayed train", t: "The train to the away game sat outside a station for two hours. The squad played cards and got to know each other. Morale up, form down a touch.", who: "squad", m: 0.3, f: -1, w: 1 },
  { h: "Shirt swap fan", t: "A famous player from a rival club asked to swap shirts with {p} after their last meeting. {p} is still talking about it. Morale up.", who: "one", m: 1, w: 2 },
  { h: "Long trip blues", t: "{n} players have struggled to sleep since the last long trip. Their body clocks are all over the place. Form down.", who: "few", f: -1, w: 2 }
];

if (typeof module !== "undefined" && module.exports) module.exports = { EVENTS };
