// Floodlights unexpected events. Each club rolls for these every week.
// t: the news line ({p} is the player hit, {q} a second one, {n} how many). who: one, few, squad or gk.
// f: form change, m: morale change. w: how long it lasts in matches (1 one match, 3 a few, 0 lingering, which
// moves the player's own form and morale for good instead of a short effect).
const EVENTS = [
  // ---------- travel and hotel trouble ----------
  { t: "{p} got left at the hotel before the game. The bus went without him. Squad morale down for the match.", who: "squad", m: -0.5, w: 1 },
  { t: "Away fans let off firecrackers outside the team hotel all night. {n} players are shattered and their form is down.", who: "few", f: -1, w: 1 },
  { t: "The hotel double booked the rooms and half the squad shared beds. Nobody slept. Form down for a match.", who: "squad", f: -1, w: 1 },
  { t: "The team bus broke down on the motorway. The lads arrived ninety minutes before kick off and stiff as boards.", who: "squad", f: -1, w: 1 },
  { t: "A fire alarm went off at 3am and the whole squad stood in the car park in their pants. Form down this week.", who: "squad", f: -1, w: 1 },
  { t: "The hotel chef served something dodgy. {p} and {q} spent the night being sick. Form down for a couple of games.", who: "few", f: -1, w: 2 },
  { t: "The flight was delayed five hours and the squad ate airport sandwiches for dinner. Morale down for the match.", who: "squad", m: -0.5, w: 1 },
  { t: "{p} lost his passport at the airport and missed the flight. He turned up a day late and rattled. Form down.", who: "one", f: -2, w: 2 },
  { t: "The hotel pool was closed for cleaning and the lads sulked about it all day. Morale down a touch.", who: "squad", m: -0.3, w: 1 },
  { t: "The hotel upgraded everyone to suites by mistake. Best night of sleep all season. Form up for the match.", who: "squad", f: 1, w: 1 },
  { t: "The hotel laid on a surprise barbecue by the pool. Good vibes all round. Squad morale up.", who: "squad", m: 0.5, w: 2 },
  { t: "{p} found a piano in the hotel lobby and played for an hour. The lads loved it. Morale up for the trip.", who: "squad", m: 0.4, w: 1 },
  { t: "The coach driver got lost and took the scenic route. The lads saw a castle. Neutral, but a nice day out.", who: "squad", m: 0.1, w: 1 },
  { t: "The team plane hit turbulence over the mountains and {p} has sworn off flying. He is a mess this week.", who: "one", f: -2, m: -0.5, w: 1 },
  { t: "{p} slept through his alarm and missed the bus to training. Fined a week's wages. Morale down.", who: "one", m: -1, w: 3 },
  { t: "A wedding party in the hotel bar sang until dawn. {n} players are running on fumes.", who: "few", f: -1, w: 1 },
  { t: "The hotel gym had no weights, just two yoga mats. The lads did a stretching session instead and felt great.", who: "squad", f: 1, w: 1 },
  { t: "The bus had no air conditioning on the hottest day of the year. Everyone arrived dripping. Form down.", who: "squad", f: -1, w: 1 },
  { t: "Someone booked the team into a hotel next to a nightclub. Thump thump thump until four. Form down.", who: "squad", f: -1, w: 1 },
  { t: "The airline lost the kit bags. The squad warmed up in borrowed training gear. Form down for the match.", who: "squad", f: -1, w: 1 },

  // ---------- family and life ----------
  { t: "{p} became a dad this week. The baby arrived early and healthy. His morale is through the roof.", who: "one", m: 2, w: 0 },
  { t: "{p} got engaged on the beach at the weekend. He is floating around training. Morale way up.", who: "one", m: 1.5, w: 0 },
  { t: "{p} got married over the international break. Big smile, big form.", who: "one", f: 1, m: 1, w: 0 },
  { t: "{p} is going through a messy break up. His head is somewhere else. Form and morale down.", who: "one", f: -2, m: -1, w: 0 },
  { t: "{p} lost his grandad this week. The squad wore black armbands. He plays, but his form is down for a bit.", who: "one", f: -2, m: -1, w: 3 },
  { t: "{p} moved house and spent three days carrying boxes. Legs heavy for a match.", who: "one", f: -1, w: 1 },
  { t: "{p} bought a dog. The whole dressing room has met the dog. Morale up for everyone.", who: "squad", m: 0.3, w: 1 },
  { t: "{p} passed his driving test at the fourth attempt. The lads have not stopped laughing. Morale up.", who: "squad", m: 0.3, w: 1 },
  { t: "{p} has a new baby at home and is getting two hours of sleep a night. Form down for a few games.", who: "one", f: -1, w: 3 },
  { t: "{p} got a surprise visit from his parents, who flew in to watch him play. Morale up.", who: "one", m: 1, w: 2 },
  { t: "{p} finished his coaching badges in the evenings. He is seeing the game differently. Form up.", who: "one", f: 1, w: 0 },
  { t: "{p} had a tooth out and his face is the size of a football. Form down for a match.", who: "one", f: -1, w: 1 },
  { t: "{p} got sunburned on his day off and cannot wear a shirt without wincing. Form down for a match.", who: "one", f: -1, w: 1 },
  { t: "{p} won a charity bake off against the kitchen staff. Nobody can believe it. Morale up.", who: "one", m: 1, w: 2 },
  { t: "{p} has had a falling out with his agent. Lots of angry phone calls. Morale down.", who: "one", m: -1, w: 0 },
  { t: "{p} got a new puppy and it chewed through his match boots. He played in borrowed ones. Form down for a match.", who: "one", f: -1, w: 1 },
  { t: "{p} celebrated his birthday with the squad. Cake, songs, a bit of a sing song. Morale up.", who: "squad", m: 0.3, w: 1 },
  { t: "{p} opened a restaurant in town and it got a glowing review. He cannot stop grinning. Morale up.", who: "one", m: 1, w: 0 },
  { t: "{p} has family visiting from home for a month. Home cooking every night. Form up.", who: "one", f: 1, w: 3 },
  { t: "{p} is homesick. He has been quiet at training all week. Morale down.", who: "one", m: -1, w: 3 },

  // ---------- dressing room ----------
  { t: "Team bonding dinner went brilliantly. Karaoke, speeches, the lot. Squad morale up.", who: "squad", m: 0.5, w: 0 },
  { t: "The team bonding paintball day ended with {p} and {q} not speaking. Morale down for both.", who: "few", m: -1, w: 3 },
  { t: "{p} did an interview trashing the coach. He and two mates in the dressing room have lost the mood.", who: "few", m: -1, w: 3 },
  { t: "The keeper did an interview trashing the coach. His morale and that of two team mates is down.", who: "gk", m: -1, w: 3 },
  { t: "The squad went go karting and {p} beat everyone. Bragging rights for a month. Morale up all round.", who: "squad", m: 0.3, w: 1 },
  { t: "A row broke out at training over a bad tackle. {p} and {q} had to be pulled apart. Morale down for both.", who: "few", m: -1, f: -1, w: 2 },
  { t: "The captain called a players only meeting after the last result. Honest words. Form up for the squad.", who: "squad", f: 1, w: 1 },
  { t: "The senior players took the youngsters out for dinner. Good for the group. Morale up.", who: "squad", m: 0.4, w: 2 },
  { t: "{p} was caught talking about his team mates in a leaked voice note. Awkward. Squad morale down.", who: "squad", m: -0.5, w: 2 },
  { t: "The squad had a five a side tournament with the staff. The chef scored a hat trick. Morale up.", who: "squad", m: 0.3, w: 1 },
  { t: "{p} has been made vice captain. He is walking taller already. Form up.", who: "one", f: 1, m: 1, w: 0 },
  { t: "{p} lost the vice captaincy after a row with the staff. Morale down.", who: "one", m: -1, w: 0 },
  { t: "A dressing room prank went too far. {p} found his car wrapped in cling film. He did not laugh.", who: "one", m: -1, w: 1 },
  { t: "A dressing room prank went down a storm. {p} filled {q}'s locker with balloons. Morale up all round.", who: "squad", m: 0.3, w: 1 },
  { t: "The squad fell out over the music in the dressing room. {p} has banned everything but jazz. Morale down.", who: "squad", m: -0.3, w: 1 },
  { t: "The squad started a group chat without the manager. Lots of jokes. Morale up a touch.", who: "squad", m: 0.2, w: 1 },
  { t: "{p} gave a fiery speech before training about standards. The lads ran through walls. Form up.", who: "squad", f: 1, w: 1 },
  { t: "{p} and {q} have become best mates and are always first out for training. Form up for both.", who: "few", f: 1, w: 3 },
  { t: "The squad is split over a card game debt. {p} says he is owed money. Morale down for a few.", who: "few", m: -0.5, w: 2 },
  { t: "Some of the lads turned up late for a team meeting and got a rollicking. Form down for them.", who: "few", f: -1, w: 1 },

  // ---------- fans and media ----------
  { t: "The fans unveiled a huge banner of {p} before training. He was close to tears. Morale up.", who: "one", m: 1, w: 3 },
  { t: "A section of the fans booed {p} after the last game. He has gone very quiet. Morale down.", who: "one", m: -1, w: 2 },
  { t: "The local paper ran a front page calling the squad lazy. The lads are furious and fired up. Form up.", who: "squad", f: 1, w: 1 },
  { t: "A pundit called {p} the most overrated player in the league. He wants to prove them wrong. Form up.", who: "one", f: 2, w: 2 },
  { t: "A pundit called {p} the most overrated player in the league. He read it and believed it. Form down.", who: "one", f: -1, m: -0.5, w: 2 },
  { t: "{p} went viral for a backheel in training. Ten million views. He is loving life. Morale up.", who: "one", m: 1, w: 2 },
  { t: "{p} went viral for falling over in training. Ten million views. He is not loving life. Morale down.", who: "one", m: -0.5, w: 1 },
  { t: "The fans sang {p}'s name for ten straight minutes in the last game. He is buzzing. Form up.", who: "one", f: 1, m: 0.5, w: 2 },
  { t: "A fan ran onto the training pitch and nutmegged {p}. The video is everywhere. The squad is howling.", who: "squad", m: 0.3, w: 1 },
  { t: "{p} was voted fans' player of the month. Morale up.", who: "one", m: 1, w: 2 },
  { t: "The club shop sold out of {p} shirts. He has signed four hundred of them this week. Morale up.", who: "one", m: 0.5, w: 2 },
  { t: "{p} got into a spat with a fan on social media. The club made him apologise. Morale down.", who: "one", m: -1, w: 2 },
  { t: "The fans held a protest about ticket prices outside training. It was loud. Squad form down for a match.", who: "squad", f: -1, w: 1 },
  { t: "A radio phone in spent an hour slating {p}. His mum rang him about it. Morale down.", who: "one", m: -1, w: 1 },
  { t: "A documentary crew has been following the squad all week. Everyone is on their best behaviour. Form up.", who: "squad", f: 1, w: 1 },
  { t: "The documentary crew caught {p} moaning about tactics. Awkward meeting with the gaffer. Morale down.", who: "one", m: -1, w: 2 },
  { t: "The fans raised money for a local hospital in {p}'s name. He visited the ward. Morale up.", who: "one", m: 1, w: 0 },
  { t: "A newspaper claimed {p} wants to leave. He says it is nonsense but the squad is unsettled. Morale down.", who: "squad", m: -0.3, w: 1 },
  { t: "The squad did a hospital visit with Christmas presents. Everyone came back humbled and happy. Morale up.", who: "squad", m: 0.4, w: 2 },
  { t: "The club mascot tripped over {p} in the tunnel and the whole stadium laughed. Nobody is bothered.", who: "one", m: 0.1, w: 1 },

  // ---------- training ----------
  { t: "The training pitch flooded and the squad trained in a car park. Form down for the match.", who: "squad", f: -1, w: 1 },
  { t: "{p} has been staying behind after training every day to practise free kicks. Form up.", who: "one", f: 1, w: 3 },
  { t: "The fitness coach brought in a new sprint programme. The lads are flying. Form up for a few games.", who: "squad", f: 1, w: 2 },
  { t: "The fitness coach brought in a new sprint programme and overdid it. Dead legs everywhere. Form down.", who: "squad", f: -1, w: 1 },
  { t: "{p} tweaked a muscle in the warm up and is playing through it. Form down for a match.", who: "one", f: -2, w: 1 },
  { t: "{p} has been on a new diet and dropped three kilos. He looks sharp. Form up.", who: "one", f: 1, w: 0 },
  { t: "{p} has been on a new diet and is miserable. No pasta, no joy. Morale down.", who: "one", m: -0.5, w: 2 },
  { t: "A sports psychologist did a session with the squad. {p} says it changed everything. Form up.", who: "few", f: 1, w: 3 },
  { t: "The club brought in a set piece coach. The first session was a revelation. Form up for the squad.", who: "squad", f: 1, w: 1 },
  { t: "{p} skipped a recovery session to go shopping. The staff are not happy. Form down.", who: "one", f: -1, m: -0.5, w: 1 },
  { t: "The new training ground gym opened. The lads have never lifted so much. Form up.", who: "squad", f: 1, w: 2 },
  { t: "{p} has been doing yoga at dawn and swears by it. Form up.", who: "one", f: 1, w: 3 },
  { t: "The groundsman cut the training pitch too short and {p} slipped all session. Form down for a match.", who: "one", f: -1, w: 1 },
  { t: "The gaffer ran a brutal double session in the rain. Bodies sore but minds sharp. Form up.", who: "squad", f: 1, w: 1 },
  { t: "The club cancelled a day off to review the last game. Grumbles everywhere. Morale down.", who: "squad", m: -0.3, w: 1 },
  { t: "Training was cancelled because of snow. The lads built a snowman shaped like the gaffer. Morale up.", who: "squad", m: 0.3, w: 1 },
  { t: "{p} has been training with the first team keeper coach for fun and loves it. Morale up.", who: "one", m: 0.5, w: 2 },
  { t: "{p} won every sprint test this week. He is in the shape of his life. Form up.", who: "one", f: 2, w: 2 },
  { t: "{p} finished last in every sprint test this week. The staff have had words. Form down.", who: "one", f: -1, w: 1 },
  { t: "A video analysis session showed {p} exactly where he keeps losing his man. He has fixed it. Form up.", who: "one", f: 1, w: 0 },

  // ---------- contracts and money ----------
  { t: "{p} signed a new contract and the club gave him a cake with his face on it. Morale way up.", who: "one", m: 1.5, w: 0 },
  { t: "{p} has rejected a new contract offer and the fans have noticed. Morale down.", who: "one", m: -1, w: 0 },
  { t: "{p} found out a team mate earns double what he does. He has not taken it well. Morale down.", who: "one", m: -1, w: 3 },
  { t: "The club paid a win bonus early. Everyone got a nice surprise in the bank. Morale up.", who: "squad", m: 0.4, w: 1 },
  { t: "The club is late paying bonuses. Lots of muttering in the canteen. Morale down.", who: "squad", m: -0.4, w: 2 },
  { t: "{p} got a boot deal with a big brand. Free boots for life. Morale up.", who: "one", m: 1, w: 0 },
  { t: "{p} lost a boot deal after a poor run. He is wearing a rival brand and sulking. Morale down.", who: "one", m: -0.5, w: 2 },
  { t: "{p} was fined for being late three times. He says the traffic is not his fault. Morale down.", who: "one", m: -0.5, w: 1 },
  { t: "The board gave the squad a bonus for the last win. Everyone is happy. Morale up.", who: "squad", m: 0.3, w: 1 },
  { t: "{p} is in a row with the club over image rights. Lawyers involved. Morale down.", who: "one", m: -1, w: 3 },
  { t: "{p} donated a week's wages to a local food bank and the whole town loved it. Morale up.", who: "one", m: 1, w: 2 },
  { t: "The club gave everyone a new car for the season. The car park looks like a showroom. Morale up.", who: "squad", m: 0.3, w: 1 },

  // ---------- transfer talk ----------
  { t: "{p} is being linked with a move to a bigger club and has gone off the boil. Form down.", who: "one", f: -1, m: -0.5, w: 2 },
  { t: "{p} was linked with a move and told the press he is going nowhere. The fans love him for it. Morale up.", who: "one", m: 1, w: 2 },
  { t: "A scout from a big club was spotted at training watching {p}. He played out of his skin. Form up.", who: "one", f: 1, w: 1 },
  { t: "{p}'s agent has been shopping him around behind the club's back. The gaffer found out. Morale down.", who: "one", m: -1, w: 3 },
  { t: "The club turned down a bid for {p} and told him he is the future. Morale up.", who: "one", m: 1, w: 2 },
  { t: "Rumours of a big signing in the same position have {p} and {q} looking over their shoulders. Form up.", who: "few", f: 1, w: 2 },
  { t: "Rumours of a big signing in the same position have {p} and {q} worried. Morale down.", who: "few", m: -0.5, w: 2 },
  { t: "{p} went public saying he wants to leave. The dressing room is cold on him. Morale down.", who: "one", m: -1.5, w: 0 },

  // ---------- health and small knocks ----------
  { t: "A cold went round the dressing room. {n} players are sniffing and sneezing. Form down for a match.", who: "few", f: -1, w: 1 },
  { t: "{p} has hay fever and the pitch was just cut. He could not see the ball. Form down for a match.", who: "one", f: -1, w: 1 },
  { t: "{p} had a wisdom tooth out and is on soup. Form down for a couple of games.", who: "one", f: -1, w: 2 },
  { t: "{p} got stung by a wasp at training and his hand is huge. Form down for a match.", who: "one", f: -1, w: 1 },
  { t: "A stomach bug swept the squad. {n} players spent the week near a toilet. Form down.", who: "few", f: -2, w: 1 },
  { t: "{p} had a full medical check and the doctors say he is in the best shape of his career. Form up.", who: "one", f: 1, w: 3 },
  { t: "{p} tried a cryotherapy chamber and came out a new man. Form up for a match.", who: "one", f: 1, w: 1 },
  { t: "{p} got a new pair of contact lenses and says the goal looks bigger. Form up.", who: "one", f: 1, w: 3 },
  { t: "{p} cannot shake a cough. He is playing but puffing. Form down.", who: "one", f: -1, w: 2 },
  { t: "The club doctor found {p} was dehydrated all week. Water bottles everywhere now. Form up.", who: "one", f: 1, w: 1 },
  { t: "{p} slept on a bad pillow and has a stiff neck. He cannot head a ball. Form down for a match.", who: "one", f: -1, w: 1 },
  { t: "{p} had a massage therapist in from abroad and feels ten years younger. Form up.", who: "one", f: 1, w: 2 },

  // ---------- weather and grounds ----------
  { t: "A heatwave hit training all week. {n} players are wilting. Form down for the match.", who: "few", f: -1, w: 1 },
  { t: "A cold snap froze the training pitches. The squad trained indoors on a tiny court and loved it. Morale up.", who: "squad", m: 0.3, w: 1 },
  { t: "The stadium lights failed during a night session. The lads played a game of hide and seek. Morale up.", who: "squad", m: 0.2, w: 1 },
  { t: "The club put in a new pitch and it plays like a carpet. Form up for the squad at home.", who: "squad", f: 1, w: 2 },
  { t: "The roof of the dressing room leaked and {p}'s kit got soaked. He played in a spare. Form down for a match.", who: "one", f: -1, w: 1 },
  { t: "Fog cancelled training and the squad went to the cinema together. Morale up.", who: "squad", m: 0.3, w: 1 },
  { t: "The sprinklers came on during a tactics talk. Everyone got drenched and the gaffer laughed first. Morale up.", who: "squad", m: 0.3, w: 1 },
  { t: "A storm knocked the power out at the training ground. Cold showers all week. Form down.", who: "squad", f: -1, w: 1 },

  // ---------- form and confidence ----------
  { t: "{p} scored a worldie in a training game and has not stopped talking about it. Form up.", who: "one", f: 1, w: 2 },
  { t: "{p} missed three open goals in training and is in his own head. Form down.", who: "one", f: -1, w: 2 },
  { t: "The gaffer told {p} he is the first name on the team sheet. He is walking on air. Form up.", who: "one", f: 1, m: 1, w: 3 },
  { t: "The gaffer told {p} he needs to do more. He took it well and has been superb. Form up.", who: "one", f: 2, w: 2 },
  { t: "The gaffer told {p} he needs to do more. He took it badly. Form down.", who: "one", f: -1, m: -1, w: 2 },
  { t: "{p} got man of the match in a training game judged by the kit man. Nobody argued. Form up.", who: "one", f: 1, w: 1 },
  { t: "{p} has lost his place in the pecking order for penalties. He is sulking. Morale down.", who: "one", m: -0.5, w: 2 },
  { t: "{p} has been handed the penalties. He has been practising all week. Form up.", who: "one", f: 1, m: 0.5, w: 2 },
  { t: "The keeper saved four penalties in training. He is unbeatable this week. Form up.", who: "gk", f: 2, w: 1 },
  { t: "The keeper let three in from the halfway line in training. Everyone is a bit worried. Form down.", who: "gk", f: -2, w: 1 },
  { t: "The keeper got a new pair of gloves from his idol. He is sticking to everything. Form up.", who: "gk", f: 1, m: 0.5, w: 2 },
  { t: "The keeper was dropped from his national squad. Morale down.", who: "gk", m: -1, w: 3 },
  { t: "The keeper got called up by his country for the first time. Morale way up.", who: "gk", m: 1.5, w: 0 },
  { t: "{p} got his first call up for his country. The whole squad clapped him in. Morale up.", who: "one", m: 1.5, w: 0 },
  { t: "{p} was dropped from his national squad. He is taking it out on the training cones. Form down.", who: "one", f: -1, m: -1, w: 2 },
  { t: "{p} came back from international duty with a winner's medal. Form up.", who: "one", f: 1, m: 1, w: 2 },
  { t: "{p} came back from international duty having played three games in a week. Shattered. Form down.", who: "one", f: -1, w: 1 },
  { t: "{p} was named in the league team of the week. Form up.", who: "one", f: 1, w: 1 },
  { t: "{p} got an award from his old school. He gave a speech and everything. Morale up.", who: "one", m: 0.5, w: 1 },
  { t: "{p} has gone twelve games without a goal in training. He is pressing too hard. Form down.", who: "one", f: -1, w: 2 },

  // ---------- odd and fun ----------
  { t: "{p} got stuck in a lift for two hours with the kit man. They are now best friends. Morale up.", who: "one", m: 0.5, w: 1 },
  { t: "A seagull stole {p}'s lunch on the training ground. The video has a million views. Morale up all round.", who: "squad", m: 0.2, w: 1 },
  { t: "{p} locked his keys in his car and had to get a taxi to the game. He arrived flustered. Form down for a match.", who: "one", f: -1, w: 1 },
  { t: "{p} won the squad fantasy league and will not stop talking about it. Morale up.", who: "one", m: 0.5, w: 2 },
  { t: "{p} lost the squad fantasy league and has to wear a dress to training. The lads are howling. Morale up.", who: "squad", m: 0.3, w: 1 },
  { t: "{p} adopted a stray cat that lives at the training ground. The squad calls it the gaffer. Morale up.", who: "squad", m: 0.3, w: 2 },
  { t: "{p} got a terrible haircut and refuses to take his hat off. Form down for a match.", who: "one", f: -1, w: 1 },
  { t: "{p} dyed his hair the club colours for a bet. The fans are obsessed. Morale up.", who: "one", m: 1, w: 2 },
  { t: "The squad went bowling and {p} bowled a perfect game. Nobody can believe it. Morale up.", who: "squad", m: 0.3, w: 1 },
  { t: "The squad went to an escape room and got stuck for two hours. {p} blamed everyone. Morale down a touch.", who: "squad", m: -0.2, w: 1 },
  { t: "{p} fell asleep in a team meeting and snored. The gaffer let it slide. Everyone else laughed. Morale up.", who: "squad", m: 0.2, w: 1 },
  { t: "{p} appeared on a cooking show and burned everything. The squad watched it together. Morale up.", who: "squad", m: 0.3, w: 1 },
  { t: "{p} did a charity skydive. He cried the whole way down. The squad respects it. Morale up.", who: "one", m: 1, w: 2 },
  { t: "{p} got a tattoo of the club badge. Big commitment. The fans are thrilled. Morale up.", who: "one", m: 1, w: 3 },
  { t: "{p} got a tattoo of the wrong club badge by mistake. He is not talking about it. Morale down.", who: "one", m: -0.5, w: 1 },
  { t: "The club cat walked across the pitch during training and everyone stopped to watch. Nothing changed, nice moment.", who: "squad", m: 0.1, w: 1 },
  { t: "{p} swapped shirts with his childhood hero in a friendly and framed it. Morale up.", who: "one", m: 1, w: 2 },
  { t: "{p} won a game of chess against the gaffer. The gaffer wants a rematch. Morale up.", who: "one", m: 0.5, w: 1 },
  { t: "{p} got a parking ticket at the stadium on match day. He is fuming. Morale down for a match.", who: "one", m: -0.3, w: 1 },
  { t: "{p} found out he has a long lost cousin in the opposition squad. They swapped numbers. Nice story, no effect.", who: "one", w: 1 },
  { t: "A local school named their football pitch after {p}. He opened it in person. Morale up.", who: "one", m: 1, w: 2 },
  { t: "{p} got a speeding fine driving to training. He says he was late because of the dog. Morale down.", who: "one", m: -0.5, w: 1 },
  { t: "{p} has learned the local language and gave his first interview in it. The fans loved it. Morale up.", who: "one", m: 1, w: 3 },
  { t: "{p} got lost on his first drive to a new training ground and ended up in the next town. Form down for a match.", who: "one", f: -1, w: 1 },
  { t: "{p} and {q} started a podcast. It is mostly about biscuits. The squad loves it. Morale up.", who: "few", m: 0.5, w: 2 },
  { t: "{p} was pictured eating a kebab at 2am. The club had a word. Form down for a match.", who: "one", f: -1, m: -0.5, w: 1 },
  { t: "The squad found an old photo of the gaffer with a mullet. It is now the dressing room wallpaper. Morale up.", who: "squad", m: 0.3, w: 1 },
  { t: "{p} rescued a dog from a river on his day off. Local hero. Morale up.", who: "one", m: 1, w: 2 },
  { t: "{p} tried to cook for the squad and set off every alarm in the building. Morale up anyway.", who: "squad", m: 0.2, w: 1 },
  { t: "{p} got invited to a film premiere and walked the red carpet. He is insufferable now. Morale up.", who: "one", m: 0.5, w: 1 },

  // ---------- the club ----------
  { t: "The club chairman visited training and shook every hand. Nice touch. Morale up.", who: "squad", m: 0.3, w: 1 },
  { t: "The club chairman visited training and read out a list of what is wrong. Morale down.", who: "squad", m: -0.4, w: 1 },
  { t: "The club announced a new stadium plan. The squad is excited about the future. Morale up.", who: "squad", m: 0.4, w: 2 },
  { t: "The club announced cuts to the canteen. No more free toast. Mutiny brewing. Morale down.", who: "squad", m: -0.4, w: 2 },
  { t: "The club brought back free toast. Order is restored. Morale up.", who: "squad", m: 0.4, w: 1 },
  { t: "A club legend came in to speak to the squad. {p} could not stop smiling. Form up.", who: "squad", f: 1, w: 1 },
  { t: "The club launched a new kit and it is a beauty. Everyone wants to play in it. Morale up.", who: "squad", m: 0.3, w: 1 },
  { t: "The club launched a new kit and it is hideous. {p} says he looks like a deckchair. Morale down a touch.", who: "squad", m: -0.2, w: 1 },
  { t: "The club announced a tour of Asia for the summer. Half the squad is thrilled, half is already tired. No effect.", who: "squad", w: 1 },
  { t: "The club's kit man retired after thirty years. Big emotional goodbye. Morale up for the week.", who: "squad", m: 0.3, w: 1 },
  { t: "The club got a new team bus with massage seats. Travel will never be the same. Form up for the next trip.", who: "squad", f: 1, w: 1 },
  { t: "The club got a sponsorship from a local bakery. Free pastries every morning. Form down, morale up.", who: "squad", f: -1, m: 0.5, w: 1 },
  { t: "The club put {p} on the cover of the match day programme. He bought fifty copies for his family. Morale up.", who: "one", m: 0.5, w: 1 },
  { t: "The club's new nutritionist banned sauce. The squad is in mourning. Morale down.", who: "squad", m: -0.3, w: 2 },
  { t: "The club's new nutritionist is a genius and everyone has more energy. Form up.", who: "squad", f: 1, w: 2 },

  // ---------- rivals and the league ----------
  { t: "A rival club's player mocked {p} on social media before the game. He is out for revenge. Form up.", who: "one", f: 2, w: 1 },
  { t: "The squad watched the rivals lose on the telly together. Big cheers. Morale up.", who: "squad", m: 0.3, w: 1 },
  { t: "The rivals won a trophy and paraded it past the training ground. Salt in the wound. Morale down.", who: "squad", m: -0.3, w: 1 },
  { t: "{p} was asked which rival player he would sign and gave an honest answer. The fans are not happy. Morale down.", who: "one", m: -0.5, w: 1 },
  { t: "The league named {p} in its young player shortlist. Form up.", who: "one", f: 1, m: 0.5, w: 2 },
  { t: "A former team mate at a rival club told the press {p} was lazy. {p} is running twice as hard. Form up.", who: "one", f: 2, w: 2 },
  { t: "The referee's association apologised to the club for a bad decision last week. The squad feels vindicated. Morale up.", who: "squad", m: 0.3, w: 1 },
  { t: "A manager at another club called the squad soft in an interview. The lads are raging. Form up.", who: "squad", f: 1, w: 1 },

  // ---------- gaffer and staff ----------
  { t: "The gaffer took the squad out for pizza after a good week of training. Morale up.", who: "squad", m: 0.3, w: 1 },
  { t: "The gaffer threw a water bottle across the dressing room after training. Nobody is smiling. Morale down.", who: "squad", m: -0.4, w: 1 },
  { t: "The gaffer praised {p} in front of the whole squad. He has grown a foot. Form up.", who: "one", f: 1, m: 1, w: 2 },
  { t: "The gaffer tore into {p} in front of the whole squad. He is shaken. Form down.", who: "one", f: -1, m: -1, w: 2 },
  { t: "The gaffer switched off his phone and took the squad hiking. Fresh air, clear heads. Form up.", who: "squad", f: 1, w: 1 },
  { t: "The physio's magic hands sorted out a knot in {p}'s back he has had for a year. Form up.", who: "one", f: 1, w: 3 },
  { t: "The club's analyst found a weakness in the next opponent and the squad is buzzing to use it. Form up.", who: "squad", f: 1, w: 1 },
  { t: "The gaffer forgot {p}'s name in a press conference. The lads will not let it go. Morale up for everyone but him.", who: "one", m: -0.3, w: 1 },
  { t: "The gaffer gave the squad three days off out of the blue. Everyone came back refreshed. Form up.", who: "squad", f: 1, w: 1 },
  { t: "The gaffer cancelled days off until further notice. Grim faces. Morale down.", who: "squad", m: -0.4, w: 1 },
  { t: "The goalkeeping coach brought in a crossing machine that never misses. The keeper has been peppered all week. Form up.", who: "gk", f: 1, w: 2 },
  { t: "The keeper and the keeper coach had a loud row about positioning. Morale down.", who: "gk", m: -1, w: 2 },
  { t: "The keeper has been working on his kicking with a rugby coach. It is paying off. Form up.", who: "gk", f: 1, w: 3 },
  { t: "The keeper left his gloves at home and played in a pair from the club shop. Form down for a match.", who: "gk", f: -1, w: 1 },
  { t: "The keeper gave a motivational talk to the academy kids and came back inspired. Morale up.", who: "gk", m: 1, w: 2 },
  { t: "The keeper has a new superstition and must touch both posts before kick off. Nobody minds. No effect.", who: "gk", w: 1 },
  { t: "The keeper has been sleeping badly since the baby came. Form down for a few games.", who: "gk", f: -1, w: 3 },
  { t: "The keeper was voted best in the league by his fellow pros. Morale up.", who: "gk", m: 1, f: 1, w: 2 },
  { t: "The club bought a new scoreboard and the keeper keeps checking the clock. Form down for a match.", who: "gk", f: -1, w: 1 },
  { t: "The keeper wrote a children's book about a brave goalkeeper. It sold out locally. Morale up.", who: "gk", m: 1, w: 2 }
];

if (typeof module !== "undefined" && module.exports) module.exports = { EVENTS };
