// Floodlights real world travel dataset. One row per club in the game world:
// [city, country, latitude, longitude, main airport, airport code, budget hotel, standard hotel, luxury hotel].
// Cities, coordinates and airports are the real ones for each club's home. The hotels are real hotels in that
// city (chains in smaller towns, landmark hotels in big ones). Distances are computed from the coordinates by
// floodlights/condition.js, prices are generated from distance and class, nothing live is fetched.
const TRAVEL = {
  // ---------- Premier League ----------
  "Arsenal": ["London", "England", 51.5549, -0.1084, "London Heathrow", "LHR", "Premier Inn London Holborn", "Hilton London Metropole", "The Langham, London"],
  "Aston Villa": ["Birmingham", "England", 52.5092, -1.8847, "Birmingham", "BHX", "Premier Inn Birmingham City Centre (New Street)", "Hyatt Regency Birmingham", "The Grand Hotel Birmingham"],
  "Bournemouth": ["Bournemouth", "England", 50.7352, -1.8383, "Bournemouth", "BOH", "Premier Inn Bournemouth Central", "Hilton Bournemouth", "Harbour Heights Hotel, Poole"],
  "Brentford": ["London", "England", 51.4907, -0.2886, "London Heathrow", "LHR", "Premier Inn London Brentford", "Hilton London Syon Park", "The Langham, London"],
  "Brighton": ["Brighton", "England", 50.8616, -0.0837, "London Gatwick", "LGW", "Premier Inn Brighton City Centre", "Hilton Brighton Metropole", "The Grand Brighton"],
  "Burnley": ["Burnley", "England", 53.7890, -2.2302, "Manchester", "MAN", "Premier Inn Burnley", "Holiday Inn Express Burnley", "Crow Wood Hotel and Spa"],
  "Chelsea": ["London", "England", 51.4817, -0.1910, "London Heathrow", "LHR", "Premier Inn London Kensington (Earl's Court)", "Millennium Hotel London Knightsbridge", "The Berkeley"],
  "Crystal Palace": ["London", "England", 51.3983, -0.0855, "London Gatwick", "LGW", "Premier Inn London Croydon Town Centre", "Hilton London Croydon", "The Savoy"],
  "Everton": ["Liverpool", "England", 53.4388, -2.9663, "Liverpool John Lennon", "LPL", "Premier Inn Liverpool City Centre (Albert Dock)", "Hilton Liverpool City Centre", "Titanic Hotel Liverpool"],
  "Fulham": ["London", "England", 51.4750, -0.2217, "London Heathrow", "LHR", "Premier Inn London Putney Bridge", "Hilton London Olympia", "The Dorchester"],
  "Leeds United": ["Leeds", "England", 53.7778, -1.5721, "Leeds Bradford", "LBA", "Premier Inn Leeds City Centre (Leeds Arena)", "Hilton Leeds City", "The Queens Hotel Leeds"],
  "Liverpool": ["Liverpool", "England", 53.4308, -2.9608, "Liverpool John Lennon", "LPL", "Premier Inn Liverpool City Centre (Lime Street)", "Novotel Liverpool Centre", "Hope Street Hotel"],
  "Man City": ["Manchester", "England", 53.4831, -2.2004, "Manchester", "MAN", "Premier Inn Manchester City Centre (Piccadilly)", "Hilton Manchester Deansgate", "The Lowry Hotel"],
  "Man United": ["Manchester", "England", 53.4631, -2.2913, "Manchester", "MAN", "Travelodge Manchester Salford Quays", "Hotel Football Old Trafford", "The Midland Manchester"],
  "Newcastle": ["Newcastle upon Tyne", "England", 54.9756, -1.6217, "Newcastle", "NCL", "Premier Inn Newcastle City Centre (Millennium Bridge)", "Crowne Plaza Newcastle Stephenson Quarter", "Malmaison Newcastle"],
  "Nottingham Forest": ["Nottingham", "England", 52.9400, -1.1329, "East Midlands", "EMA", "Premier Inn Nottingham City Centre (Chapel Bar)", "Crowne Plaza Nottingham", "Hart's Hotel Nottingham"],
  "Sunderland": ["Sunderland", "England", 54.9144, -1.3882, "Newcastle", "NCL", "Premier Inn Sunderland City Centre", "Hilton Garden Inn Sunderland", "Seaham Hall"],
  "Tottenham": ["London", "England", 51.6042, -0.0662, "London Stansted", "STN", "Premier Inn London Tottenham Hale", "Hilton London Canary Wharf", "Claridge's"],
  "West Ham": ["London", "England", 51.5387, -0.0166, "London City", "LCY", "Premier Inn London Stratford", "Hilton London Canary Wharf", "Shangri-La The Shard, London"],
  "Wolves": ["Wolverhampton", "England", 52.5903, -2.1304, "Birmingham", "BHX", "Premier Inn Wolverhampton City Centre (Bluebrick)", "Novotel Wolverhampton", "The Mount Hotel and Conference Centre"],

  // ---------- La Liga ----------
  "Real Madrid": ["Madrid", "Spain", 40.4531, -3.6883, "Madrid Barajas", "MAD", "ibis Madrid Centro las Ventas", "NH Collection Madrid Eurobuilding", "Four Seasons Hotel Madrid"],
  "Barcelona": ["Barcelona", "Spain", 41.3809, 2.1228, "Barcelona El Prat", "BCN", "ibis Barcelona Centro (Sagrada Familia)", "NH Collection Barcelona Gran Hotel Calderon", "Hotel Arts Barcelona"],
  "Atletico Madrid": ["Madrid", "Spain", 40.4362, -3.5995, "Madrid Barajas", "MAD", "ibis Madrid Centro las Ventas", "Melia Castilla", "Mandarin Oriental Ritz, Madrid"],
  "Athletic Bilbao": ["Bilbao", "Spain", 43.2641, -2.9494, "Bilbao", "BIO", "ibis Bilbao Centro", "NH Collection Bilbao Villa de Bilbao", "Hotel Carlton Bilbao"],
  "Real Sociedad": ["San Sebastian", "Spain", 43.3014, -1.9736, "San Sebastian", "EAS", "ibis Donostia San Sebastian", "NH Collection San Sebastian Aranzazu", "Hotel Maria Cristina, a Luxury Collection Hotel"],
  "Villarreal": ["Villarreal", "Spain", 39.9440, -0.1037, "Valencia", "VLC", "ibis Castellon", "Hotel Luz Castellon", "Las Arenas Balneario Resort, Valencia"],
  "Real Betis": ["Seville", "Spain", 37.3565, -5.9817, "Seville", "SVQ", "ibis Sevilla", "NH Collection Sevilla", "Hotel Alfonso XIII, a Luxury Collection Hotel"],
  "Sevilla": ["Seville", "Spain", 37.3840, -5.9705, "Seville", "SVQ", "ibis Sevilla", "Melia Sevilla", "Hotel Alfonso XIII, a Luxury Collection Hotel"],
  "Valencia": ["Valencia", "Spain", 39.4747, -0.3583, "Valencia", "VLC", "ibis Valencia Bonaire", "NH Valencia Las Artes", "The Westin Valencia"],
  "Celta Vigo": ["Vigo", "Spain", 42.2119, -8.7397, "Vigo", "VGO", "ibis Styles Vigo", "Hotel Ciudad de Vigo", "Gran Hotel Nagari Boutique and Spa"],
  "Girona": ["Girona", "Spain", 41.9614, 2.8286, "Girona Costa Brava", "GRO", "ibis Girona", "Hotel Carlemany Girona", "Hotel Nord 1901"],
  "Osasuna": ["Pamplona", "Spain", 42.7968, -1.6368, "Pamplona", "PNA", "ibis Pamplona", "NH Pamplona Iruna Park", "Gran Hotel La Perla"],
  "Getafe": ["Getafe", "Spain", 40.3257, -3.7147, "Madrid Barajas", "MAD", "ibis Madrid Getafe", "Hotel Ilunion Pio XII, Madrid", "Hotel Villa Magna, Madrid"],
  "Mallorca": ["Palma", "Spain", 39.5900, 2.6300, "Palma de Mallorca", "PMI", "ibis Palma de Mallorca", "Melia Palma Bay", "Castillo Hotel Son Vida"],
  "Rayo Vallecano": ["Madrid", "Spain", 40.3918, -3.6587, "Madrid Barajas", "MAD", "ibis Madrid Centro las Ventas", "NH Madrid Nacional", "Hotel Wellington Madrid"],
  "Espanyol": ["Cornella de Llobregat", "Spain", 41.3478, 2.0756, "Barcelona El Prat", "BCN", "ibis Barcelona Cornella", "Hotel Fira Congress Barcelona", "Hotel Arts Barcelona"],
  "Alaves": ["Vitoria-Gasteiz", "Spain", 42.8371, -2.6880, "Bilbao", "BIO", "ibis Vitoria Gasteiz", "NH Canciller Ayala Vitoria", "Gran Hotel Lakua"],
  "Elche": ["Elche", "Spain", 38.2669, -0.6611, "Alicante-Elche", "ALC", "ibis Elche", "Hotel Huerto del Cura", "Asia Gardens Hotel and Thai Spa, Benidorm"],
  "Levante": ["Valencia", "Spain", 39.4947, -0.3650, "Valencia", "VLC", "ibis Valencia Bonaire", "Hotel Sorolla Palace", "Caro Hotel"],
  "Real Oviedo": ["Oviedo", "Spain", 43.3663, -5.8700, "Asturias", "OVD", "ibis Oviedo", "NH Oviedo Principado", "Hotel de la Reconquista"],

  // ---------- Serie A ----------
  "Inter Milan": ["Milan", "Italy", 45.4781, 9.1240, "Milan Malpensa", "MXP", "ibis Milano Centro", "NH Milano Touring", "Four Seasons Hotel Milano"],
  "AC Milan": ["Milan", "Italy", 45.4781, 9.1240, "Milan Linate", "LIN", "ibis Milano Centro", "Hilton Milan", "Armani Hotel Milano"],
  "Juventus": ["Turin", "Italy", 45.1096, 7.6413, "Turin", "TRN", "ibis Styles Torino Porta Nuova", "NH Torino Centro", "Principi di Piemonte UNA Esperienze"],
  "Napoli": ["Naples", "Italy", 40.8279, 14.1930, "Naples", "NAP", "ibis Styles Napoli Garibaldi", "NH Napoli Panorama", "Grand Hotel Vesuvio"],
  "Atalanta": ["Bergamo", "Italy", 45.7089, 9.6806, "Milan Bergamo", "BGY", "B&B Hotel Bergamo", "NH Bergamo", "Relais San Lorenzo"],
  "Roma": ["Rome", "Italy", 41.9339, 12.4544, "Rome Fiumicino", "FCO", "ibis Styles Roma Vintage", "NH Collection Roma Giustiniano", "Hotel de Russie, a Rocco Forte Hotel"],
  "Fiorentina": ["Florence", "Italy", 43.7808, 11.2823, "Florence", "FLR", "B&B Hotel Firenze Novoli", "NH Firenze", "Four Seasons Hotel Firenze"],
  "Lazio": ["Rome", "Italy", 41.9339, 12.4544, "Rome Fiumicino", "FCO", "ibis Styles Roma Vintage", "Hilton Rome Eur La Lama", "Hotel Hassler Roma"],
  "Bologna": ["Bologna", "Italy", 44.4927, 11.3097, "Bologna", "BLQ", "ibis Bologna Centro", "NH Bologna de la Gare", "Grand Hotel Majestic gia Baglioni"],
  "Como": ["Como", "Italy", 45.8120, 9.0729, "Milan Malpensa", "MXP", "B&B Hotel Como", "Hilton Lake Como", "Villa d'Este"],
  "Torino": ["Turin", "Italy", 45.0417, 7.6500, "Turin", "TRN", "ibis Styles Torino Porta Nuova", "AC Hotel Torino by Marriott", "Grand Hotel Sitea"],
  "Udinese": ["Udine", "Italy", 46.0816, 13.2000, "Trieste", "TRS", "B&B Hotel Udine", "Hotel Astoria Italia Udine", "Hotel Friuli Udine"],
  "Genoa": ["Genoa", "Italy", 44.4164, 8.9525, "Genoa", "GOA", "B&B Hotel Genova", "NH Genova Centro", "Grand Hotel Savoia"],
  "Cagliari": ["Cagliari", "Italy", 39.2000, 9.1372, "Cagliari Elmas", "CAG", "B&B Hotel Cagliari", "Hotel Regina Margherita", "Palazzo Doglio"],
  "Parma": ["Parma", "Italy", 44.7950, 10.3384, "Bologna", "BLQ", "ibis Styles Parma Toscanini", "NH Parma", "Grand Hotel de la Ville Parma"],
  "Sassuolo": ["Reggio Emilia", "Italy", 44.7142, 10.6457, "Bologna", "BLQ", "B&B Hotel Reggio Emilia", "Mercure Reggio Emilia Centro Astoria", "Hotel Posta Reggio Emilia"],
  "Cremonese": ["Cremona", "Italy", 45.1407, 10.0327, "Milan Linate", "LIN", "B&B Hotel Cremona", "Hotel Impero Cremona", "Delle Arti Design Hotel"],
  "Pisa": ["Pisa", "Italy", 43.7256, 10.4015, "Pisa", "PSA", "B&B Hotel Pisa", "NH Pisa", "Bagni di Pisa Palace and Spa"],
  "Lecce": ["Lecce", "Italy", 40.3650, 18.2095, "Brindisi", "BDS", "B&B Hotel Lecce", "Hilton Garden Inn Lecce", "Patria Palace Hotel Lecce"],
  "Verona": ["Verona", "Italy", 45.4353, 10.9686, "Verona Villafranca", "VRN", "B&B Hotel Verona", "NH Verona", "Hotel Due Torri"],

  // ---------- Bundesliga ----------
  "Bayern Munich": ["Munich", "Germany", 48.2188, 11.6247, "Munich", "MUC", "ibis Munchen City", "Hilton Munich Park", "Hotel Vier Jahreszeiten Kempinski Munchen"],
  "Bayer Leverkusen": ["Leverkusen", "Germany", 51.0383, 7.0022, "Cologne Bonn", "CGN", "ibis Koln Centrum", "Lindner Hotel Leverkusen BayArena", "Excelsior Hotel Ernst, Cologne"],
  "Borussia Dortmund": ["Dortmund", "Germany", 51.4926, 7.4519, "Dortmund", "DTM", "ibis Dortmund City", "Radisson Blu Hotel Dortmund", "Hotel l'Arrivee Dortmund"],
  "RB Leipzig": ["Leipzig", "Germany", 51.3459, 12.3482, "Leipzig Halle", "LEJ", "ibis Leipzig City", "Radisson Blu Hotel Leipzig", "Steigenberger Grandhotel Handelshof Leipzig"],
  "Eintracht Frankfurt": ["Frankfurt", "Germany", 50.0686, 8.6454, "Frankfurt", "FRA", "ibis Frankfurt Centrum", "Hilton Frankfurt City Centre", "Steigenberger Icon Frankfurter Hof"],
  "Stuttgart": ["Stuttgart", "Germany", 48.7922, 9.2320, "Stuttgart", "STR", "ibis Stuttgart Centrum", "Maritim Hotel Stuttgart", "Althoff Hotel am Schlossgarten"],
  "Wolfsburg": ["Wolfsburg", "Germany", 52.4319, 10.8039, "Hannover", "HAJ", "ibis Wolfsburg", "Courtyard by Marriott Wolfsburg", "The Ritz-Carlton, Wolfsburg"],
  "Borussia Monchengladbach": ["Monchengladbach", "Germany", 51.1746, 6.3855, "Dusseldorf", "DUS", "ibis Monchengladbach", "Leonardo Hotel Monchengladbach", "Hotel Palace St. George"],
  "Freiburg": ["Freiburg", "Germany", 48.0210, 7.8298, "Basel-Mulhouse", "BSL", "B&B Hotel Freiburg", "Novotel Freiburg am Konzerthaus", "Colombi Hotel"],
  "Hoffenheim": ["Sinsheim", "Germany", 49.2381, 8.8879, "Frankfurt", "FRA", "B&B Hotel Heidelberg", "Leonardo Hotel Heidelberg", "Hotel Europaischer Hof Heidelberg"],
  "Mainz": ["Mainz", "Germany", 49.9842, 8.2244, "Frankfurt", "FRA", "ibis Mainz City", "Hyatt Regency Mainz", "Hilton Mainz"],
  "Werder Bremen": ["Bremen", "Germany", 53.0664, 8.8376, "Bremen", "BRE", "ibis Bremen Centrum", "Radisson Blu Hotel Bremen", "Dorint Park Hotel Bremen"],
  "Augsburg": ["Augsburg", "Germany", 48.3232, 10.8864, "Munich", "MUC", "ibis Augsburg Konigsplatz", "Dorint An der Kongresshalle Augsburg", "Steigenberger Drei Mohren Augsburg"],
  "Union Berlin": ["Berlin", "Germany", 52.4573, 13.5681, "Berlin Brandenburg", "BER", "ibis Berlin Mitte", "Hilton Berlin", "Hotel Adlon Kempinski Berlin"],
  "FC Koln": ["Cologne", "Germany", 50.9335, 6.8752, "Cologne Bonn", "CGN", "ibis Koln Centrum", "Dorint An der Messe Koln", "Excelsior Hotel Ernst"],
  "Hamburg": ["Hamburg", "Germany", 53.5873, 9.8986, "Hamburg", "HAM", "ibis Hamburg City", "Radisson Blu Hotel Hamburg", "Fairmont Hotel Vier Jahreszeiten Hamburg"],
  "St Pauli": ["Hamburg", "Germany", 53.5546, 9.9676, "Hamburg", "HAM", "ibis Hamburg St. Pauli Messe", "Empire Riverside Hotel", "The Fontenay Hamburg"],
  "Heidenheim": ["Heidenheim", "Germany", 48.6686, 10.1392, "Stuttgart", "STR", "Lobinger Hotel Parkhotel, Giengen an der Brenz", "Taste Hotel Heidenheim", "Schlosshotel Hellenstein"],

  // ---------- Ligue 1 ----------
  "PSG": ["Paris", "France", 48.8414, 2.2530, "Paris Charles de Gaulle", "CDG", "ibis Paris Porte de Versailles", "Pullman Paris Tour Eiffel", "Le Bristol Paris"],
  "Marseille": ["Marseille", "France", 43.2699, 5.3958, "Marseille Provence", "MRS", "ibis Marseille Centre Gare Saint Charles", "Radisson Blu Hotel Marseille Vieux Port", "InterContinental Marseille Hotel Dieu"],
  "Monaco": ["Monaco", "Monaco", 43.7276, 7.4155, "Nice Cote d'Azur", "NCE", "ibis Nice Centre Gare", "Novotel Monte Carlo", "Hotel de Paris Monte-Carlo"],
  "Lyon": ["Lyon", "France", 45.7653, 4.9820, "Lyon Saint-Exupery", "LYS", "ibis Lyon Centre Perrache", "Radisson Blu Hotel Lyon", "Villa Florentine"],
  "Lille": ["Lille", "France", 50.6120, 3.1305, "Lille", "LIL", "ibis Lille Centre Gares", "Crowne Plaza Lille Euralille", "L'Hermitage Gantois"],
  "Nice": ["Nice", "France", 43.7052, 7.1927, "Nice Cote d'Azur", "NCE", "ibis Nice Centre Gare", "Hyatt Regency Nice Palais de la Mediterranee", "Hotel Negresco"],
  "Lens": ["Lens", "France", 50.4328, 2.8151, "Lille", "LIL", "ibis Lens", "Hotel Lensotel", "L'Hermitage Gantois, Lille"],
  "Rennes": ["Rennes", "France", 48.1075, -1.7128, "Rennes Bretagne", "RNS", "ibis Rennes Centre Gare Sud", "Mercure Rennes Centre Gare", "Balthazar Hotel and Spa Rennes"],
  "Strasbourg": ["Strasbourg", "France", 48.5600, 7.7550, "Strasbourg", "SXB", "ibis Strasbourg Centre Gare", "Hilton Strasbourg", "Hotel Regent Petite France"],
  "Toulouse": ["Toulouse", "France", 43.5831, 1.4342, "Toulouse Blagnac", "TLS", "ibis Toulouse Centre", "Crowne Plaza Toulouse", "La Cour des Consuls Hotel and Spa"],
  "Nantes": ["Nantes", "France", 47.2559, -1.5248, "Nantes Atlantique", "NTE", "ibis Nantes Centre Gare Sud", "Radisson Blu Hotel Nantes", "Oceania Hotel de France Nantes"],
  "Brest": ["Brest", "France", 48.4028, -4.4617, "Brest Bretagne", "BES", "ibis Brest Centre", "Oceania Brest Centre", "Hotel Vauban Brest"],
  "Auxerre": ["Auxerre", "France", 47.7866, 3.5888, "Paris Orly", "ORY", "ibis Auxerre Centre", "Mercure Auxerre Centre", "Hotel Le Maxime Auxerre"],
  "Angers": ["Angers", "France", 47.4604, -0.5307, "Nantes Atlantique", "NTE", "ibis Angers Centre Chateau", "Mercure Angers Centre Gare", "Hotel d'Anjou Angers"],
  "Lorient": ["Lorient", "France", 47.7486, -3.3690, "Lorient Bretagne Sud", "LRT", "ibis Lorient Centre", "Mercure Lorient Centre", "Hotel Les Sables Blancs, Concarneau"],
  "Le Havre": ["Le Havre", "France", 49.4989, 0.1697, "Paris Charles de Gaulle", "CDG", "ibis Le Havre Centre", "Mercure Le Havre Centre Bassin du Commerce", "Hotel Vent d'Ouest"],
  "Metz": ["Metz", "France", 49.1097, 6.1597, "Luxembourg", "LUX", "ibis Metz Centre Gare", "Mercure Metz Centre", "Hotel La Citadelle Metz"],
  "Paris FC": ["Paris", "France", 48.8186, 2.2531, "Paris Orly", "ORY", "ibis Paris Porte de Versailles", "Novotel Paris Centre Tour Eiffel", "Shangri-La Paris"],

  // ---------- Eredivisie ----------
  "Ajax": ["Amsterdam", "Netherlands", 52.3143, 4.9419, "Amsterdam Schiphol", "AMS", "ibis Amsterdam Centre", "NH Collection Amsterdam Barbizon Palace", "Waldorf Astoria Amsterdam"],
  "PSV": ["Eindhoven", "Netherlands", 51.4417, 5.4675, "Eindhoven", "EIN", "ibis Eindhoven Centre", "NH Collection Eindhoven Centre", "Van der Valk Hotel Eindhoven"],
  "Feyenoord": ["Rotterdam", "Netherlands", 51.8939, 4.5231, "Rotterdam The Hague", "RTM", "ibis Rotterdam City Centre", "Hilton Rotterdam", "Mainport Hotel Rotterdam"],
  "AZ Alkmaar": ["Alkmaar", "Netherlands", 52.6125, 4.7420, "Amsterdam Schiphol", "AMS", "ibis Amsterdam City West", "Golden Tulip Alkmaar", "Grand Hotel Amrath Amsterdam"],
  "Twente": ["Enschede", "Netherlands", 52.2367, 6.8375, "Amsterdam Schiphol", "AMS", "ibis Styles Enschede", "Van der Valk Hotel Enschede", "Landgoed de Wilmersberg"],
  "Utrecht": ["Utrecht", "Netherlands", 52.0785, 5.1462, "Amsterdam Schiphol", "AMS", "ibis Utrecht", "NH Utrecht", "Grand Hotel Karel V"],
  "Go Ahead Eagles": ["Deventer", "Netherlands", 52.2583, 6.1686, "Amsterdam Schiphol", "AMS", "ibis Styles Deventer", "Postillion Hotel Deventer", "Hotel Gaia Deventer"],
  "Sparta Rotterdam": ["Rotterdam", "Netherlands", 51.9183, 4.4316, "Rotterdam The Hague", "RTM", "ibis Rotterdam City Centre", "Novotel Rotterdam Brainpark", "Hotel New York Rotterdam"],
  "Heerenveen": ["Heerenveen", "Netherlands", 52.9603, 5.9403, "Amsterdam Schiphol", "AMS", "Fletcher Hotel Heidehof, Heerenveen", "Van der Valk Hotel Wolvega Heerenveen", "Landgoed Lauswolt, Beetsterzwaag"],
  "NEC": ["Nijmegen", "Netherlands", 51.8227, 5.8307, "Eindhoven", "EIN", "ibis Styles Nijmegen Centre", "Van der Valk Hotel Nijmegen-Lent", "Sanadome Hotel and Spa Nijmegen"],
  "Groningen": ["Groningen", "Netherlands", 53.2074, 6.5878, "Groningen Eelde", "GRQ", "ibis Groningen", "NH Groningen", "Prinsenhof Groningen"],
  "Fortuna Sittard": ["Sittard", "Netherlands", 50.9983, 5.8572, "Maastricht Aachen", "MST", "ibis Styles Sittard", "Van der Valk Hotel Stein-Urmond", "Chateau St. Gerlach, Valkenburg"],
  "PEC Zwolle": ["Zwolle", "Netherlands", 52.5195, 6.1230, "Amsterdam Schiphol", "AMS", "ibis Zwolle", "Bilderberg Grand Hotel Wientjes", "Van der Valk Hotel Zwolle"],
  "Heracles": ["Almelo", "Netherlands", 52.3433, 6.6464, "Amsterdam Schiphol", "AMS", "Fletcher Hotel Almelo", "Van der Valk Hotel Hengelo", "Landgoed de Wilmersberg, De Lutte"],
  "NAC Breda": ["Breda", "Netherlands", 51.5947, 4.7540, "Eindhoven", "EIN", "ibis Breda Centre", "Golden Tulip Keyser Breda", "Hotel Nassau Breda"],
  "Excelsior": ["Rotterdam", "Netherlands", 51.9122, 4.5222, "Rotterdam The Hague", "RTM", "ibis Rotterdam City Centre", "Inntel Hotels Rotterdam Centre", "Hotel New York Rotterdam"],
  "Volendam": ["Volendam", "Netherlands", 52.4969, 5.0617, "Amsterdam Schiphol", "AMS", "ibis Amsterdam City West", "Hotel Spaander Volendam", "Waldorf Astoria Amsterdam"],
  "Telstar": ["Velsen", "Netherlands", 52.4575, 4.6391, "Amsterdam Schiphol", "AMS", "ibis Amsterdam City West", "Van der Valk Hotel Haarlem", "Hotel Pulitzer Amsterdam"],

  // ---------- Primeira Liga ----------
  "Benfica": ["Lisbon", "Portugal", 38.7527, -9.1848, "Lisbon Humberto Delgado", "LIS", "ibis Lisboa Centro Saldanha", "NH Collection Lisboa Liberdade", "Four Seasons Hotel Ritz Lisbon"],
  "Porto": ["Porto", "Portugal", 41.1617, -8.5836, "Porto Francisco Sa Carneiro", "OPO", "ibis Porto Centro", "NH Collection Porto Batalha", "The Yeatman"],
  "Sporting CP": ["Lisbon", "Portugal", 38.7613, -9.1609, "Lisbon Humberto Delgado", "LIS", "ibis Lisboa Centro Saldanha", "Sheraton Lisboa Hotel and Spa", "Pestana Palace Lisboa"],
  "Braga": ["Braga", "Portugal", 41.5625, -8.4297, "Porto Francisco Sa Carneiro", "OPO", "ibis Braga Centro", "Melia Braga Hotel and Spa", "Vila Gale Collection Braga"],
  "Vitoria Guimaraes": ["Guimaraes", "Portugal", 41.4458, -8.3010, "Porto Francisco Sa Carneiro", "OPO", "ibis Guimaraes Centro", "Hotel de Guimaraes", "Pousada Mosteiro de Guimaraes"],
  "Famalicao": ["Vila Nova de Famalicao", "Portugal", 41.4061, -8.5247, "Porto Francisco Sa Carneiro", "OPO", "B&B Hotel Famalicao", "Hotel Moutados", "The Yeatman, Porto"],
  "Rio Ave": ["Vila do Conde", "Portugal", 41.3539, -8.7428, "Porto Francisco Sa Carneiro", "OPO", "ibis Porto Sao Joao", "Hotel Santana Vila do Conde", "InterContinental Porto Palacio das Cardosas"],
  "Estoril": ["Estoril", "Portugal", 38.7098, -9.4000, "Lisbon Humberto Delgado", "LIS", "ibis Lisboa Centro Saldanha", "Hotel Vila Gale Estoril", "Palacio Estoril Hotel Golf and Wellness"],
  "Casa Pia": ["Lisbon", "Portugal", 38.7303, -9.2080, "Lisbon Humberto Delgado", "LIS", "ibis Lisboa Centro Saldanha", "Hotel Lisboa Plaza", "Tivoli Avenida Liberdade Lisboa"],
  "Gil Vicente": ["Barcelos", "Portugal", 41.5367, -8.6214, "Porto Francisco Sa Carneiro", "OPO", "ibis Braga Centro", "Hotel do Terco Barcelos", "Vila Gale Collection Braga"],
  "Moreirense": ["Moreira de Conegos", "Portugal", 41.3803, -8.3503, "Porto Francisco Sa Carneiro", "OPO", "ibis Guimaraes Centro", "Hotel de Guimaraes", "Pousada Mosteiro de Guimaraes"],
  "Arouca": ["Arouca", "Portugal", 40.9316, -8.2478, "Porto Francisco Sa Carneiro", "OPO", "Hotel Sao Pedro Arouca", "Hotel Arouca", "The Yeatman, Porto"],
  "Estrela Amadora": ["Amadora", "Portugal", 38.7533, -9.2289, "Lisbon Humberto Delgado", "LIS", "ibis Lisboa Alfragide", "Hotel Lisboa Plaza", "Four Seasons Hotel Ritz Lisbon"],
  "Nacional": ["Funchal", "Portugal", 32.6500, -16.9353, "Madeira", "FNC", "Hotel Windsor Funchal", "Pestana Casino Park Hotel", "Belmond Reid's Palace"],
  "Santa Clara": ["Ponta Delgada", "Portugal", 37.7367, -25.6753, "Ponta Delgada Joao Paulo II", "PDL", "Hotel Talisman Ponta Delgada", "Hotel Marina Atlantico", "Azor Hotel"],
  "Tondela": ["Tondela", "Portugal", 40.5181, -8.0828, "Porto Francisco Sa Carneiro", "OPO", "Hotel SJ Tondela", "Hotel Montebelo Viseu", "Montebelo Viseu Congress Hotel"],
  "AVS": ["Vila das Aves", "Portugal", 41.3747, -8.4147, "Porto Francisco Sa Carneiro", "OPO", "ibis Guimaraes Centro", "Hotel Cidnay Santo Tirso", "The Yeatman, Porto"],
  "Alverca": ["Alverca do Ribatejo", "Portugal", 38.8975, -9.0353, "Lisbon Humberto Delgado", "LIS", "ibis Lisboa Centro Saldanha", "Hotel Vila Gale Opera Lisboa", "Four Seasons Hotel Ritz Lisbon"],

  // ---------- Super Lig ----------
  "Galatasaray": ["Istanbul", "Turkey", 41.1035, 28.9906, "Istanbul", "IST", "ibis Istanbul Zeytinburnu", "Hilton Istanbul Bosphorus", "Ciragan Palace Kempinski Istanbul"],
  "Fenerbahce": ["Istanbul", "Turkey", 40.9877, 29.0366, "Istanbul Sabiha Gokcen", "SAW", "ibis Istanbul Zeytinburnu", "Wyndham Grand Istanbul Kalamis Marina", "Four Seasons Hotel Istanbul at the Bosphorus"],
  "Besiktas": ["Istanbul", "Turkey", 41.0393, 28.9945, "Istanbul", "IST", "ibis Istanbul Zeytinburnu", "Conrad Istanbul Bosphorus", "Shangri-La Bosphorus, Istanbul"],
  "Trabzonspor": ["Trabzon", "Turkey", 40.9966, 39.7795, "Trabzon", "TZX", "Ramada Plaza by Wyndham Trabzon", "Hilton Garden Inn Trabzon", "Zorlu Grand Hotel Trabzon"],
  "Basaksehir": ["Istanbul", "Turkey", 41.1063, 28.8083, "Istanbul", "IST", "ibis Istanbul Zeytinburnu", "Holiday Inn Istanbul Airport", "The Ritz-Carlton, Istanbul"],
  "Samsunspor": ["Samsun", "Turkey", 41.2847, 36.2814, "Samsun Carsamba", "SZF", "ibis Styles Samsun", "Sheraton Grand Samsun", "Anemon Samsun Hotel"],
  "Goztepe": ["Izmir", "Turkey", 38.3893, 27.0773, "Izmir Adnan Menderes", "ADB", "ibis Izmir Alsancak", "Hilton Izmir", "Swissotel Buyuk Efes Izmir"],
  "Kasimpasa": ["Istanbul", "Turkey", 41.0369, 28.9719, "Istanbul", "IST", "ibis Istanbul Zeytinburnu", "Radisson Blu Hotel Istanbul Pera", "Pera Palace Hotel"],
  "Antalyaspor": ["Antalya", "Turkey", 36.9025, 30.7236, "Antalya", "AYT", "ibis Styles Antalya", "Ramada Plaza Antalya", "Akra Hotel"],
  "Alanyaspor": ["Alanya", "Turkey", 36.5450, 32.0083, "Gazipasa Alanya", "GZP", "Kleopatra Dreams Beach Hotel", "Ramada Resort by Wyndham Alanya", "Rixos Premium Tekirova"],
  "Rizespor": ["Rize", "Turkey", 41.0272, 40.5097, "Trabzon", "TZX", "Ricosta Hotel Rize", "Ramada Plaza by Wyndham Rize", "Ridos Thermal Hotel and Spa"],
  "Konyaspor": ["Konya", "Turkey", 37.9353, 32.4642, "Konya", "KYA", "ibis Konya", "Hilton Garden Inn Konya", "Dedeman Konya Hotel and Convention Center"],
  "Gaziantep": ["Gaziantep", "Turkey", 37.0872, 37.4036, "Gaziantep", "GZT", "ibis Gaziantep", "Novotel Gaziantep", "Shimall Hotel Gaziantep"],
  "Kayserispor": ["Kayseri", "Turkey", 38.7444, 35.5347, "Kayseri Erkilet", "ASR", "ibis Kayseri", "Hilton Garden Inn Kayseri", "Radisson Blu Hotel Kayseri"],
  "Eyupspor": ["Istanbul", "Turkey", 41.0511, 28.9361, "Istanbul", "IST", "ibis Istanbul Zeytinburnu", "Hilton Istanbul Bomonti", "Raffles Istanbul"],
  "Kocaelispor": ["Izmit", "Turkey", 40.7625, 29.9272, "Istanbul Sabiha Gokcen", "SAW", "ibis Styles Izmit", "Hilton Garden Inn Kocaeli Sakarya", "Wellborn Luxury Hotel"],
  "Genclerbirligi": ["Ankara", "Turkey", 39.8921, 32.8407, "Ankara Esenboga", "ESB", "ibis Ankara Airport", "Hilton Garden Inn Ankara Gimat", "JW Marriott Hotel Ankara"],
  "Karagumruk": ["Istanbul", "Turkey", 41.0254, 28.9440, "Istanbul", "IST", "ibis Istanbul Zeytinburnu", "Mercure Istanbul Topkapi", "Pera Palace Hotel"],

  // ---------- Saudi Pro League ----------
  "Al-Hilal": ["Riyadh", "Saudi Arabia", 24.7847, 46.8367, "King Khalid International", "RUH", "ibis Riyadh Olaya Street", "Hilton Riyadh Hotel and Residences", "The Ritz-Carlton, Riyadh"],
  "Al-Nassr": ["Riyadh", "Saudi Arabia", 24.7322, 46.6694, "King Khalid International", "RUH", "ibis Riyadh Olaya Street", "Crowne Plaza Riyadh RDC", "Four Seasons Hotel Riyadh"],
  "Al-Ittihad": ["Jeddah", "Saudi Arabia", 21.6248, 39.1769, "King Abdulaziz International", "JED", "ibis Jeddah Malik Road", "Hilton Jeddah", "The Ritz-Carlton, Jeddah"],
  "Al-Ahli": ["Jeddah", "Saudi Arabia", 21.6248, 39.1769, "King Abdulaziz International", "JED", "ibis Jeddah City Center", "Crowne Plaza Jeddah", "Rosewood Jeddah"],
  "Al-Qadsiah": ["Khobar", "Saudi Arabia", 26.2172, 50.1971, "King Fahd International", "DMM", "ibis Al Khobar", "Hilton Garden Inn Al Khobar", "Kempinski Al Othman Hotel Al Khobar"],
  "Al-Shabab": ["Riyadh", "Saudi Arabia", 24.6800, 46.6900, "King Khalid International", "RUH", "ibis Riyadh Olaya Street", "Radisson Blu Hotel Riyadh", "Mandarin Oriental Al Faisaliah, Riyadh"],
  "Al-Ettifaq": ["Dammam", "Saudi Arabia", 26.4344, 50.1033, "King Fahd International", "DMM", "ibis Dammam", "Sheraton Dammam Hotel and Convention Centre", "Movenpick Hotel Al Khobar"],
  "Al-Taawoun": ["Buraidah", "Saudi Arabia", 26.3600, 43.9750, "Prince Nayef bin Abdulaziz", "ELQ", "ibis Buraidah", "Movenpick Hotel Qassim", "Braira Al Qassim Hotel"],
  "Al-Fateh": ["Al-Hasa", "Saudi Arabia", 25.3794, 49.5867, "Al-Ahsa International", "HOF", "Golden Tulip Al Hasa", "Al Ahsa InterContinental", "Al Koot Heritage Hotel"],
  "Al-Khaleej": ["Saihat", "Saudi Arabia", 26.4817, 50.0411, "King Fahd International", "DMM", "ibis Dammam", "Novotel Dammam Business Park", "Kempinski Al Othman Hotel Al Khobar"],
  "Al-Fayha": ["Al-Majma'ah", "Saudi Arabia", 25.9000, 45.3600, "King Khalid International", "RUH", "Raoum Inn Majmaa", "Boudl Al Majmaa", "Four Seasons Hotel Riyadh"],
  "Damac": ["Khamis Mushait", "Saudi Arabia", 18.3000, 42.7300, "Abha", "AHB", "Golden Inn Khamis Mushait", "Mercure Hotel Khamis Mushait", "Abha Palace Hotel"],
  "Al-Riyadh": ["Riyadh", "Saudi Arabia", 24.7200, 46.7000, "King Khalid International", "RUH", "ibis Riyadh Olaya Street", "Novotel Riyadh Al Anoud", "Burj Rafal Hotel Riyadh"],
  "Al-Okhdood": ["Najran", "Saudi Arabia", 17.4917, 44.1322, "Najran", "EAM", "Najran Hotel", "Florida Inn Hotel Najran", "Park Inn by Radisson Najran"],
  "Al-Kholood": ["Ar Rass", "Saudi Arabia", 25.8667, 43.5000, "Prince Nayef bin Abdulaziz", "ELQ", "Boudl Al Rass", "Braira Al Rass", "Saif Boutique Hotel International"],
  "Neom": ["Tabuk", "Saudi Arabia", 28.3838, 36.5550, "Tabuk", "TUU", "ibis Tabuk", "Hilton Garden Inn Tabuk", "Swiss Spirit Hotel and Suites Tabuk"],
  "Al-Najma": ["Unaizah", "Saudi Arabia", 26.0844, 43.9942, "Prince Nayef bin Abdulaziz", "ELQ", "Golden Tulip Al Waha Hotel Unayzah", "Boudl Al Nakheel Resort", "Swiss International Resort Unaizah"],
  "Al-Hazem": ["Ar Rass", "Saudi Arabia", 25.8667, 43.5000, "Prince Nayef bin Abdulaziz", "ELQ", "Boudl Al Rass", "Braira Al Rass", "Saif Boutique Hotel International"],

  // ---------- MLS ----------
  "Inter Miami": ["Fort Lauderdale", "USA", 26.1931, -80.1608, "Fort Lauderdale-Hollywood International", "FLL", "Hampton Inn Fort Lauderdale Airport North Cruise Port", "Hilton Fort Lauderdale Marina", "Four Seasons Hotel and Residences Fort Lauderdale"],
  "LAFC": ["Los Angeles", "USA", 34.0128, -118.2842, "Los Angeles International", "LAX", "Hampton Inn and Suites Los Angeles Downtown", "JW Marriott Los Angeles L.A. LIVE", "The Beverly Hills Hotel"],
  "LA Galaxy": ["Carson", "USA", 33.8644, -118.2611, "Los Angeles International", "LAX", "Hampton Inn and Suites Los Angeles Carson", "Marriott Torrance South Bay", "Terranea Resort"],
  "San Diego FC": ["San Diego", "USA", 32.7836, -117.1192, "San Diego International", "SAN", "Hampton Inn San Diego Downtown", "Marriott Marquis San Diego Marina", "Fairmont Grand Del Mar"],
  "Atlanta United": ["Atlanta", "USA", 33.7554, -84.4010, "Hartsfield-Jackson Atlanta International", "ATL", "Hampton Inn and Suites Atlanta Downtown", "Omni Atlanta Hotel at Centennial Park", "Four Seasons Hotel Atlanta"],
  "Seattle Sounders": ["Seattle", "USA", 47.5952, -122.3316, "Seattle-Tacoma International", "SEA", "Hampton Inn and Suites Seattle Downtown", "Hyatt Regency Seattle", "Fairmont Olympic Hotel"],
  "Columbus Crew": ["Columbus", "USA", 39.9686, -83.0170, "John Glenn Columbus International", "CMH", "Hampton Inn and Suites Columbus Downtown", "Hilton Columbus Downtown", "The Joseph, a Luxury Collection Hotel"],
  "FC Cincinnati": ["Cincinnati", "USA", 39.1114, -84.5222, "Cincinnati/Northern Kentucky International", "CVG", "Hampton Inn and Suites Cincinnati Downtown", "Hyatt Regency Cincinnati", "21c Museum Hotel Cincinnati"],
  "Portland Timbers": ["Portland", "USA", 45.5215, -122.6919, "Portland International", "PDX", "Hampton Inn and Suites Portland Pearl District", "Hilton Portland Downtown", "The Nines, a Luxury Collection Hotel"],
  "Austin FC": ["Austin", "USA", 30.3881, -97.7195, "Austin-Bergstrom International", "AUS", "Hampton Inn and Suites Austin Downtown", "Hilton Austin", "Four Seasons Hotel Austin"],
  "NYCFC": ["New York", "USA", 40.8296, -73.9262, "LaGuardia", "LGA", "Hampton Inn Manhattan Times Square Central", "New York Marriott Marquis", "The Plaza, A Fairmont Managed Hotel"],
  "New York Red Bulls": ["Harrison", "USA", 40.7368, -74.1503, "Newark Liberty International", "EWR", "Hampton Inn Newark Airport", "Courtyard by Marriott Newark Downtown", "The St. Regis New York"],
  "Philadelphia Union": ["Chester", "USA", 39.8322, -75.3789, "Philadelphia International", "PHL", "Hampton Inn Philadelphia Center City Convention Center", "Sheraton Philadelphia Downtown", "Four Seasons Hotel Philadelphia at Comcast Center"],
  "Charlotte FC": ["Charlotte", "USA", 35.2258, -80.8528, "Charlotte Douglas International", "CLT", "Hampton Inn and Suites Charlotte Uptown", "Hilton Charlotte Uptown", "The Ritz-Carlton, Charlotte"],
  "Orlando City": ["Orlando", "USA", 28.5412, -81.3890, "Orlando International", "MCO", "Hampton Inn and Suites Orlando Downtown South", "Hyatt Regency Orlando", "Four Seasons Resort Orlando at Walt Disney World Resort"],
  "Minnesota United": ["Saint Paul", "USA", 44.9530, -93.1650, "Minneapolis-Saint Paul International", "MSP", "Hampton Inn and Suites Minneapolis Downtown", "Hyatt Regency Minneapolis", "Four Seasons Hotel Minneapolis"],

  // ---------- Scottish Premiership ----------
  "Celtic": ["Glasgow", "Scotland", 55.8497, -4.2056, "Glasgow", "GLA", "Premier Inn Glasgow City Centre (George Square)", "Hilton Glasgow", "Kimpton Blythswood Square Hotel"],
  "Rangers": ["Glasgow", "Scotland", 55.8532, -4.3094, "Glasgow", "GLA", "Premier Inn Glasgow City Centre (Argyle Street)", "Radisson Blu Hotel Glasgow", "Kimpton Blythswood Square Hotel"],
  "Hearts": ["Edinburgh", "Scotland", 55.9390, -3.2322, "Edinburgh", "EDI", "Premier Inn Edinburgh City Centre (Haymarket)", "Hilton Edinburgh Carlton", "The Balmoral"],
  "Hibernian": ["Edinburgh", "Scotland", 55.9617, -3.1655, "Edinburgh", "EDI", "Premier Inn Edinburgh City Centre (Princes Street)", "Radisson Blu Hotel Edinburgh City Centre", "Waldorf Astoria Edinburgh The Caledonian"],
  "Aberdeen": ["Aberdeen", "Scotland", 57.1591, -2.0888, "Aberdeen", "ABZ", "Premier Inn Aberdeen City Centre", "Hilton Aberdeen TECA", "The Chester Hotel"],
  "Dundee United": ["Dundee", "Scotland", 56.4747, -2.9690, "Dundee", "DND", "Premier Inn Dundee Centre", "Malmaison Dundee", "Apex City Quay Hotel and Spa"],
  "Motherwell": ["Motherwell", "Scotland", 55.7805, -3.9802, "Glasgow", "GLA", "Premier Inn Glasgow Motherwell", "Dalziel Park Hotel", "Crossbasket Castle"],
  "Kilmarnock": ["Kilmarnock", "Scotland", 55.6042, -4.5083, "Glasgow Prestwick", "PIK", "Premier Inn Kilmarnock", "The Park Hotel Kilmarnock", "Trump Turnberry"],
  "St Mirren": ["Paisley", "Scotland", 55.8534, -4.4292, "Glasgow", "GLA", "Premier Inn Glasgow Airport", "Holiday Inn Glasgow Airport", "Mar Hall Golf and Spa Resort"],
  "Dundee": ["Dundee", "Scotland", 56.4753, -2.9719, "Dundee", "DND", "Premier Inn Dundee Centre", "Hotel Indigo Dundee", "Apex City Quay Hotel and Spa"],
  "Falkirk": ["Falkirk", "Scotland", 55.9914, -3.7580, "Edinburgh", "EDI", "Premier Inn Falkirk Central", "Leapark Hotel Grangemouth", "Airth Castle Hotel and Spa"],
  "Livingston": ["Livingston", "Scotland", 55.8855, -3.5231, "Edinburgh", "EDI", "Premier Inn Livingston", "Mercure Livingston Hotel", "Dalmahoy Hotel and Country Club"],

  // ---------- Championship ----------
  "Leicester": ["Leicester", "England", 52.6204, -1.1422, "East Midlands", "EMA", "Premier Inn Leicester City Centre", "Hilton Leicester", "Stapleford Park"],
  "Southampton": ["Southampton", "England", 50.9058, -1.3911, "Southampton", "SOU", "Premier Inn Southampton City Centre", "Hilton at the Ageas Bowl", "The Pig in the Wall"],
  "Ipswich": ["Ipswich", "England", 52.0550, 1.1446, "London Stansted", "STN", "Premier Inn Ipswich Town Centre", "Novotel Ipswich Centre", "Salthouse Harbour Hotel"],
  "Sheffield United": ["Sheffield", "England", 53.3703, -1.4710, "Doncaster Sheffield", "DSA", "Premier Inn Sheffield City Centre (Angel Street)", "Mercure Sheffield St Paul's Hotel and Spa", "Leopold Hotel Sheffield"],
  "West Brom": ["West Bromwich", "England", 52.5092, -1.9639, "Birmingham", "BHX", "Premier Inn West Bromwich Town Centre", "Holiday Inn Express Birmingham Oldbury", "Hotel du Vin Birmingham"],
  "Middlesbrough": ["Middlesbrough", "England", 54.5783, -1.2170, "Teesside International", "MME", "Premier Inn Middlesbrough Town Centre", "Holiday Inn Express Middlesbrough Centre Square", "Rockliffe Hall"],
  "Norwich": ["Norwich", "England", 52.6222, 1.3091, "Norwich", "NWI", "Premier Inn Norwich City Centre (Duke Street)", "Holiday Inn Norwich City", "The Assembly House Norwich"],
  "Watford": ["Watford", "England", 51.6498, -0.4015, "London Luton", "LTN", "Premier Inn Watford Central", "Hilton London Watford", "The Grove, Hertfordshire"],
  "Coventry": ["Coventry", "England", 52.4481, -1.4956, "Birmingham", "BHX", "Premier Inn Coventry City Centre (Belgrade Plaza)", "DoubleTree by Hilton Coventry Building Society Arena", "Coombe Abbey Hotel"],
  "Stoke": ["Stoke-on-Trent", "England", 52.9884, -2.1755, "Manchester", "MAN", "Premier Inn Stoke-on-Trent City Centre", "DoubleTree by Hilton Stoke-on-Trent", "Moddershall Oaks Country Spa Retreat"],
  "Birmingham": ["Birmingham", "England", 52.4756, -1.8681, "Birmingham", "BHX", "Premier Inn Birmingham City Centre (Bull Ring)", "Clayton Hotel Birmingham", "Hotel du Vin Birmingham"],
  "Wrexham": ["Wrexham", "Wales", 53.0514, -2.9992, "Liverpool John Lennon", "LPL", "Premier Inn Wrexham Town Centre", "Ramada Plaza by Wyndham Wrexham", "Rossett Hall Hotel"],
  "Blackburn": ["Blackburn", "England", 53.7286, -2.4892, "Manchester", "MAN", "Premier Inn Blackburn Town Centre", "Mercure Blackburn Dunkenhalgh Hotel and Spa", "Stanley House Hotel and Spa"],
  "Hull": ["Hull", "England", 53.7467, -0.3675, "Humberside", "HUY", "Premier Inn Hull City Centre", "DoubleTree by Hilton Hull", "Willerby Manor Hotel"],
  "Millwall": ["London", "England", 51.4860, -0.0509, "London City", "LCY", "Premier Inn London Southwark (Borough Market)", "Hilton London Tower Bridge", "Shangri-La The Shard, London"],
  "Preston": ["Preston", "England", 53.7722, -2.6881, "Manchester", "MAN", "Premier Inn Preston Central", "Holiday Inn Preston", "Bartle Hall Hotel"],
  "Portsmouth": ["Portsmouth", "England", 50.7964, -1.0639, "Southampton", "SOU", "Premier Inn Portsmouth City Centre", "Holiday Inn Portsmouth", "Marriott Portsmouth Hotel"],
  "QPR": ["London", "England", 51.5093, -0.2322, "London Heathrow", "LHR", "Premier Inn London Hammersmith", "Hilton London Olympia", "The Dorchester"],

  // ---------- Argentina ----------
  "Boca Juniors": ["Buenos Aires", "Argentina", -34.6356, -58.3647, "Buenos Aires Ezeiza", "EZE", "ibis Buenos Aires Congreso", "NH Collection Buenos Aires Centro Historico", "Four Seasons Hotel Buenos Aires"],
  "River Plate": ["Buenos Aires", "Argentina", -34.5453, -58.4498, "Buenos Aires Ezeiza", "EZE", "ibis Buenos Aires Congreso", "Hilton Buenos Aires", "Alvear Palace Hotel"],
  "Racing Club": ["Avellaneda", "Argentina", -34.6673, -58.3684, "Buenos Aires Ezeiza", "EZE", "ibis Buenos Aires Congreso", "NH Buenos Aires Tango", "Palacio Duhau - Park Hyatt Buenos Aires"],
  "Independiente": ["Avellaneda", "Argentina", -34.6704, -58.3711, "Buenos Aires Ezeiza", "EZE", "ibis Buenos Aires Congreso", "Sheraton Buenos Aires Hotel and Convention Center", "Four Seasons Hotel Buenos Aires"],
  "San Lorenzo": ["Buenos Aires", "Argentina", -34.6523, -58.4397, "Buenos Aires Ezeiza", "EZE", "ibis Buenos Aires Congreso", "NH Buenos Aires City", "Alvear Palace Hotel"],
  "Velez": ["Buenos Aires", "Argentina", -34.6353, -58.5208, "Buenos Aires Ezeiza", "EZE", "ibis Buenos Aires Congreso", "Dazzler by Wyndham Buenos Aires Palermo", "Faena Hotel Buenos Aires"],
  "Estudiantes": ["La Plata", "Argentina", -34.9138, -57.9909, "Buenos Aires Ezeiza", "EZE", "Hotel Benevento La Plata", "Hotel Corregidor La Plata", "Grand Brizo La Plata"],
  "Rosario Central": ["Rosario", "Argentina", -32.9196, -60.6755, "Rosario Islas Malvinas", "ROS", "ibis Rosario", "Esplendor by Wyndham Savoy Rosario", "Ros Tower Hotel"],
  "Talleres": ["Cordoba", "Argentina", -31.3684, -64.2461, "Cordoba Ingeniero Taravella", "COR", "ibis Cordoba", "NH Cordoba Panorama", "Sheraton Cordoba Hotel"],
  "Lanus": ["Lanus", "Argentina", -34.7183, -58.3961, "Buenos Aires Ezeiza", "EZE", "ibis Buenos Aires Congreso", "NH Buenos Aires Tango", "Palacio Duhau - Park Hyatt Buenos Aires"],
  "Newells Old Boys": ["Rosario", "Argentina", -32.9550, -60.6584, "Rosario Islas Malvinas", "ROS", "ibis Rosario", "Howard Johnson Rosario", "Ros Tower Hotel"],
  "Huracan": ["Buenos Aires", "Argentina", -34.6433, -58.3936, "Buenos Aires Ezeiza", "EZE", "ibis Buenos Aires Congreso", "NH Buenos Aires Latino", "Four Seasons Hotel Buenos Aires"],
  "Argentinos Juniors": ["Buenos Aires", "Argentina", -34.6056, -58.4737, "Buenos Aires Ezeiza", "EZE", "ibis Buenos Aires Congreso", "Dazzler by Wyndham Buenos Aires Palermo", "Alvear Palace Hotel"],
  "Banfield": ["Banfield", "Argentina", -34.7444, -58.3933, "Buenos Aires Ezeiza", "EZE", "ibis Buenos Aires Congreso", "NH Buenos Aires Tango", "Faena Hotel Buenos Aires"],
  "Belgrano": ["Cordoba", "Argentina", -31.4123, -64.2112, "Cordoba Ingeniero Taravella", "COR", "ibis Cordoba", "Howard Johnson Cordoba", "Sheraton Cordoba Hotel"],
  "Tigre": ["Victoria", "Argentina", -34.4522, -58.5456, "Buenos Aires Ezeiza", "EZE", "ibis Buenos Aires Congreso", "Hotel Intersur Recoleta, Buenos Aires", "Alvear Palace Hotel"],

  // ---------- Brasileirao ----------
  "Flamengo": ["Rio de Janeiro", "Brazil", -22.9122, -43.2302, "Rio de Janeiro Galeao", "GIG", "ibis Rio de Janeiro Botafogo", "Hilton Rio de Janeiro Copacabana", "Copacabana Palace, A Belmond Hotel"],
  "Palmeiras": ["Sao Paulo", "Brazil", -23.5275, -46.6786, "Sao Paulo Guarulhos", "GRU", "ibis Sao Paulo Paulista", "Hilton Sao Paulo Morumbi", "Palacio Tangara"],
  "Santos": ["Santos", "Brazil", -23.9509, -46.3384, "Sao Paulo Guarulhos", "GRU", "ibis Santos Gonzaga Praia", "Mercure Santos", "Sheraton Santos Hotel"],
  "Botafogo": ["Rio de Janeiro", "Brazil", -22.9122, -43.2302, "Rio de Janeiro Galeao", "GIG", "ibis Rio de Janeiro Botafogo", "Windsor Oceanico Hotel", "Fairmont Rio de Janeiro Copacabana"],
  "Corinthians": ["Sao Paulo", "Brazil", -23.5453, -46.4743, "Sao Paulo Guarulhos", "GRU", "ibis Sao Paulo Paulista", "Grand Hyatt Sao Paulo", "Rosewood Sao Paulo"],
  "Cruzeiro": ["Belo Horizonte", "Brazil", -19.8658, -43.9709, "Belo Horizonte Confins", "CNF", "ibis Belo Horizonte Liberdade", "Mercure Belo Horizonte Lourdes", "Ouro Minas Hotel"],
  "Sao Paulo": ["Sao Paulo", "Brazil", -23.6001, -46.7197, "Sao Paulo Guarulhos", "GRU", "ibis Sao Paulo Paulista", "Sheraton Sao Paulo WTC Hotel", "Hotel Unique"],
  "Gremio": ["Porto Alegre", "Brazil", -29.9731, -51.1952, "Porto Alegre Salgado Filho", "POA", "ibis Porto Alegre Centro", "Sheraton Porto Alegre Hotel", "Hotel Deville Prime Porto Alegre"],
  "Fluminense": ["Rio de Janeiro", "Brazil", -22.9122, -43.2302, "Rio de Janeiro Galeao", "GIG", "ibis Rio de Janeiro Botafogo", "Windsor Atlantica Hotel", "Copacabana Palace, A Belmond Hotel"],
  "Internacional": ["Porto Alegre", "Brazil", -30.0655, -51.2358, "Porto Alegre Salgado Filho", "POA", "ibis Porto Alegre Centro", "Plaza Sao Rafael Hotel", "Hotel Deville Prime Porto Alegre"],
  "Bahia": ["Salvador", "Brazil", -12.9788, -38.5044, "Salvador Deputado Luis Eduardo Magalhaes", "SSA", "ibis Salvador Rio Vermelho", "Sheraton da Bahia Hotel", "Fera Palace Hotel"],
  "Fortaleza": ["Fortaleza", "Brazil", -3.8071, -38.5222, "Fortaleza Pinto Martins", "FOR", "ibis Fortaleza Praia de Iracema", "Gran Marquise Hotel", "Hotel Gran Mareiro"],
  "Atletico Mineiro": ["Belo Horizonte", "Brazil", -19.9339, -44.0197, "Belo Horizonte Confins", "CNF", "ibis Belo Horizonte Liberdade", "Holiday Inn Belo Horizonte Savassi", "Ouro Minas Hotel"],
  "Vasco da Gama": ["Rio de Janeiro", "Brazil", -22.8906, -43.2285, "Rio de Janeiro Galeao", "GIG", "ibis Rio de Janeiro Botafogo", "Hilton Rio de Janeiro Copacabana", "Fairmont Rio de Janeiro Copacabana"],
  "Bragantino": ["Braganca Paulista", "Brazil", -22.9513, -46.5421, "Sao Paulo Guarulhos", "GRU", "ibis Braganca Paulista", "Hotel Nacional Inn Braganca Paulista", "Palacio Tangara, Sao Paulo"],
  "Juventude": ["Caxias do Sul", "Brazil", -29.1621, -51.1741, "Caxias do Sul Hugo Cantergiani", "CXJ", "ibis Caxias do Sul", "Intercity Caxias do Sul", "Samuara Hotel"],
  "Vitoria": ["Salvador", "Brazil", -12.9231, -38.4208, "Salvador Deputado Luis Eduardo Magalhaes", "SSA", "ibis Salvador Rio Vermelho", "Wish Hotel da Bahia", "Fera Palace Hotel"],
  "Ceara": ["Fortaleza", "Brazil", -3.8071, -38.5222, "Fortaleza Pinto Martins", "FOR", "ibis Fortaleza Praia de Iracema", "Hotel Praia Centro Fortaleza", "Gran Marquise Hotel"],
  "Sport Recife": ["Recife", "Brazil", -8.0631, -34.9025, "Recife Guararapes", "REC", "ibis Recife Boa Viagem", "Mar Hotel Conventions Recife", "Grand Mercure Recife Boa Viagem"],
  "Mirassol": ["Mirassol", "Brazil", -20.8181, -49.5203, "Sao Jose do Rio Preto", "SJP", "ibis Sao Jose do Rio Preto", "Novotel Sao Jose do Rio Preto", "JP Hotel Sao Jose do Rio Preto"],

  // ---------- Belgian Pro League ----------
  "Club Brugge": ["Bruges", "Belgium", 51.1933, 3.1806, "Brussels", "BRU", "ibis Brugge Centrum", "NH Brugge", "Hotel Dukes' Palace Brugge"],
  "Union SG": ["Brussels", "Belgium", 50.8181, 4.3269, "Brussels", "BRU", "ibis Brussels Centre Gare du Midi", "NH Collection Brussels Grand Sablon", "Hotel Amigo, a Rocco Forte Hotel"],
  "Genk": ["Genk", "Belgium", 50.9906, 5.5339, "Brussels", "BRU", "ibis Hasselt", "Carbon Hotel Genk", "Stiemerheide Hotel Genk"],
  "Anderlecht": ["Brussels", "Belgium", 50.8342, 4.2983, "Brussels", "BRU", "ibis Brussels Centre Gare du Midi", "Hilton Brussels Grand Place", "Steigenberger Wiltcher's"],
  "Antwerp": ["Antwerp", "Belgium", 51.2225, 4.4556, "Brussels", "BRU", "ibis Antwerpen Centrum", "Hilton Antwerp Old Town", "Hotel Julien Antwerp"],
  "Gent": ["Ghent", "Belgium", 51.0162, 3.7347, "Brussels", "BRU", "ibis Gent Centrum Opera", "NH Gent Belfort", "1898 The Post"],
  "Standard Liege": ["Liege", "Belgium", 50.6099, 5.5433, "Liege", "LGG", "ibis Liege Centre Opera", "Van der Valk Hotel Liege Congres", "Crowne Plaza Liege"],
  "Charleroi": ["Charleroi", "Belgium", 50.4147, 4.4542, "Brussels South Charleroi", "CRL", "ibis Charleroi Centre Gare", "Novotel Charleroi Centre", "Hotel Amigo, a Rocco Forte Hotel, Brussels"],
  "Westerlo": ["Westerlo", "Belgium", 51.0908, 4.9203, "Brussels", "BRU", "ibis Mechelen Centrum", "Hotel Geerts Westerlo", "Martin's Patershof, Mechelen"],
  "Mechelen": ["Mechelen", "Belgium", 51.0369, 4.4789, "Brussels", "BRU", "ibis Mechelen Centrum", "Novotel Mechelen Centrum", "Martin's Patershof"],
  "Cercle Brugge": ["Bruges", "Belgium", 51.1933, 3.1806, "Brussels", "BRU", "ibis Brugge Centrum", "Hotel Aragon Brugge", "Hotel Dukes' Palace Brugge"],
  "Sint-Truiden": ["Sint-Truiden", "Belgium", 50.8178, 5.1792, "Brussels", "BRU", "ibis Hasselt", "Hotel Stayen Sint-Truiden", "Radisson Blu Hotel Hasselt"],
  "OH Leuven": ["Leuven", "Belgium", 50.8686, 4.6758, "Brussels", "BRU", "ibis Leuven Centrum", "Novotel Leuven Centrum", "The Fourth, Leuven"],
  "Dender": ["Denderleeuw", "Belgium", 50.8858, 4.0756, "Brussels", "BRU", "ibis Aalst Centrum", "Keizershof Hotel Aalst", "Hotel Amigo, a Rocco Forte Hotel, Brussels"],
  "Zulte Waregem": ["Waregem", "Belgium", 50.8858, 3.4306, "Brussels", "BRU", "ibis Kortrijk Centrum", "Hotel Ambassade Waregem", "Parkhotel Waregem"],
  "La Louviere": ["La Louviere", "Belgium", 50.4786, 4.1811, "Brussels South Charleroi", "CRL", "ibis Charleroi Centre Gare", "Hotel Tristar La Louviere", "Hotel Amigo, a Rocco Forte Hotel, Brussels"],

  // ---------- Liga MX ----------
  "Club America": ["Mexico City", "Mexico", 19.3029, -99.1505, "Mexico City Benito Juarez", "MEX", "ibis Mexico Alameda", "Hilton Mexico City Reforma", "Four Seasons Hotel Mexico City"],
  "Monterrey": ["Guadalupe", "Mexico", 25.6690, -100.2444, "Monterrey", "MTY", "ibis Monterrey Valle", "Crowne Plaza Monterrey", "Grand Fiesta Americana Monterrey Valle"],
  "Tigres": ["San Nicolas de los Garza", "Mexico", 25.7225, -100.3119, "Monterrey", "MTY", "ibis Monterrey Valle", "NH Collection Monterrey", "Live Aqua Urban Resort Monterrey"],
  "Chivas": ["Zapopan", "Mexico", 20.6817, -103.4625, "Guadalajara", "GDL", "ibis Guadalajara Expo", "Hilton Guadalajara", "Grand Velas Guadalajara"],
  "Cruz Azul": ["Mexico City", "Mexico", 19.3029, -99.1505, "Mexico City Benito Juarez", "MEX", "ibis Mexico Alameda", "Hyatt Regency Mexico City", "The St. Regis Mexico City"],
  "Pumas": ["Mexico City", "Mexico", 19.3328, -99.1922, "Mexico City Benito Juarez", "MEX", "ibis Mexico Alameda", "Camino Real Polanco Mexico", "Las Alcobas, a Luxury Collection Hotel"],
  "Toluca": ["Toluca", "Mexico", 19.2869, -99.6667, "Toluca", "TLC", "ibis Toluca", "Fiesta Inn Toluca Centro", "Grand Fiesta Americana Toluca"],
  "Pachuca": ["Pachuca", "Mexico", 20.1053, -98.7556, "Mexico City Benito Juarez", "MEX", "ibis Pachuca", "Fiesta Inn Pachuca Gran Patio", "Camino Real Pachuca"],
  "Santos Laguna": ["Torreon", "Mexico", 25.6253, -103.3936, "Torreon", "TRC", "ibis Torreon", "Fiesta Inn Torreon La Rosita", "Crowne Plaza Torreon"],
  "Leon": ["Leon", "Mexico", 21.1114, -101.6444, "Guanajuato (Del Bajio)", "BJX", "ibis Leon", "Fiesta Inn Leon", "Hotsson Hotel Leon"],
  "Tijuana": ["Tijuana", "Mexico", 32.4967, -116.9842, "Tijuana", "TIJ", "ibis Tijuana", "Real Inn Tijuana", "Grand Hotel Tijuana"],
  "Juarez": ["Ciudad Juarez", "Mexico", 31.6981, -106.4700, "Ciudad Juarez Abraham Gonzalez", "CJS", "ibis Ciudad Juarez", "Fiesta Inn Ciudad Juarez", "Hotel Lucerna Ciudad Juarez"],
  "Necaxa": ["Aguascalientes", "Mexico", 21.9008, -102.3025, "Aguascalientes", "AGU", "ibis Aguascalientes", "Fiesta Inn Aguascalientes", "Hotel Quinta Real Aguascalientes"],
  "Queretaro": ["Queretaro", "Mexico", 20.5664, -100.4303, "Queretaro Intercontinental", "QRO", "ibis Queretaro", "Fiesta Inn Queretaro", "Casa de la Marquesa"],
  "Atlas": ["Guadalajara", "Mexico", 20.6997, -103.3269, "Guadalajara", "GDL", "ibis Guadalajara Expo", "Fiesta Americana Guadalajara", "Hyatt Regency Andares Guadalajara"],
  "Puebla": ["Puebla", "Mexico", 19.0200, -98.1858, "Puebla Hermanos Serdan", "PBC", "ibis Puebla", "Fiesta Inn Puebla FINSA", "Banyan Tree Puebla"],
  "Atlante": ["Mexico City", "Mexico", 19.3836, -99.1782, "Mexico City Benito Juarez", "MEX", "ibis Mexico Alameda", "Hilton Mexico City Reforma", "Four Seasons Hotel Mexico City"],
  "Atletico San Luis": ["San Luis Potosi", "Mexico", 22.1458, -101.0144, "San Luis Potosi Ponciano Arriaga", "SLP", "ibis San Luis Potosi", "Fiesta Inn San Luis Potosi Glorieta Juarez", "Hilton San Luis Potosi"],

  // ---------- single European clubs ----------
  "Olympiacos": ["Piraeus", "Greece", 37.9465, 23.6645, "Athens Eleftherios Venizelos", "ATH", "ibis Styles Athens Routes", "Hilton Athens", "Hotel Grande Bretagne, a Luxury Collection Hotel"],
  "RB Salzburg": ["Salzburg", "Austria", 47.8163, 12.9980, "Salzburg", "SZG", "ibis Salzburg Nord", "Radisson Blu Hotel Altstadt Salzburg", "Hotel Sacher Salzburg"],
  "Copenhagen": ["Copenhagen", "Denmark", 55.7026, 12.5722, "Copenhagen Kastrup", "CPH", "Wakeup Copenhagen Borgergade", "Radisson Blu Scandinavia Hotel Copenhagen", "Hotel d'Angleterre"],
  "Dinamo Zagreb": ["Zagreb", "Croatia", 45.8187, 15.9983, "Zagreb Franjo Tudman", "ZAG", "ibis Zagreb Centre", "Hilton Garden Inn Zagreb", "Esplanade Zagreb Hotel"],

  // ---------- La Liga 2 ----------
  "Almeria": ["Almeria", "Spain", 36.8403, -2.4356, "Almeria", "LEI", "ibis Almeria", "NH Ciudad de Almeria", "Hotel Catedral Almeria"],
  "Deportivo La Coruna": ["A Coruna", "Spain", 43.3686, -8.4176, "A Coruna", "LCG", "ibis Styles A Coruna", "NH Collection A Coruna Finisterre", "Hotel Hesperia Finisterre"],
  "Las Palmas": ["Las Palmas de Gran Canaria", "Spain", 28.1003, -15.4567, "Gran Canaria", "LPA", "ibis Las Palmas", "AC Hotel Gran Canaria", "Santa Catalina, a Royal Hideaway Hotel"],
  "Leganes": ["Leganes", "Spain", 40.3406, -3.7608, "Madrid Barajas", "MAD", "ibis Madrid Getafe", "Hotel Ilunion Pio XII, Madrid", "Hotel Villa Magna, Madrid"],
  "Real Valladolid": ["Valladolid", "Spain", 41.6443, -4.7613, "Valladolid", "VLL", "ibis Valladolid", "NH Ciudad de Valladolid", "AC Hotel Palacio de Santa Ana"],
  "Sporting Gijon": ["Gijon", "Spain", 43.5361, -5.6375, "Asturias", "OVD", "ibis Gijon", "NH Gijon", "Parador de Gijon"],
  "Real Zaragoza": ["Zaragoza", "Spain", 41.6362, -0.9019, "Zaragoza", "ZAZ", "ibis Zaragoza Centro", "NH Collection Gran Hotel de Zaragoza", "Hotel Palafox"],
  "Racing Santander": ["Santander", "Spain", 43.4713, -3.8021, "Santander Seve Ballesteros", "SDR", "ibis Santander", "NH Ciudad de Santander", "Eurostars Hotel Real"],

  // ---------- Serie B ----------
  "Palermo": ["Palermo", "Italy", 38.1514, 13.3433, "Palermo Falcone Borsellino", "PMO", "B&B Hotel Palermo Quattro Canti", "NH Palermo", "Villa Igiea, a Rocco Forte Hotel"],
  "Sampdoria": ["Genoa", "Italy", 44.4164, 8.9525, "Genoa", "GOA", "B&B Hotel Genova", "Hotel Bristol Palace", "Grand Hotel Savoia"],
  "Bari": ["Bari", "Italy", 41.1247, 16.8386, "Bari Karol Wojtyla", "BRI", "B&B Hotel Bari", "Hotel Oriente Bari", "Grande Albergo delle Nazioni"],
  "Spezia": ["La Spezia", "Italy", 44.1026, 9.8084, "Pisa", "PSA", "B&B Hotel La Spezia", "NH La Spezia", "Grand Hotel Portovenere"],
  "Venezia": ["Venice", "Italy", 45.4290, 12.3680, "Venice Marco Polo", "VCE", "B&B Hotel Venezia Mestre", "NH Venezia Rio Novo", "The Gritti Palace, a Luxury Collection Hotel"],
  "Empoli": ["Empoli", "Italy", 43.7266, 10.9550, "Florence", "FLR", "B&B Hotel Firenze Novoli", "Hotel Tazza d'Oro Empoli", "Four Seasons Hotel Firenze"],
  "Monza": ["Monza", "Italy", 45.5820, 9.3080, "Milan Linate", "LIN", "B&B Hotel Monza", "Hotel de la Ville Monza", "Four Seasons Hotel Milano"],
  "Modena": ["Modena", "Italy", 44.6318, 10.9091, "Bologna", "BLQ", "B&B Hotel Modena", "Best Western Premier Milano Palace Modena", "Casa Maria Luigia"],

  // ---------- 2. Bundesliga ----------
  "Schalke": ["Gelsenkirchen", "Germany", 51.5546, 7.0675, "Dusseldorf", "DUS", "ibis Gelsenkirchen", "Courtyard by Marriott Gelsenkirchen", "Schloss Berge"],
  "Hertha Berlin": ["Berlin", "Germany", 52.5147, 13.2395, "Berlin Brandenburg", "BER", "ibis Berlin Mitte", "Hotel Palace Berlin", "Hotel Adlon Kempinski Berlin"],
  "Kaiserslautern": ["Kaiserslautern", "Germany", 49.4347, 7.7765, "Frankfurt", "FRA", "B&B Hotel Kaiserslautern", "Dorint Hotel Kaiserslautern", "Hotel Barbarossahof"],
  "Fortuna Dusseldorf": ["Dusseldorf", "Germany", 51.2615, 6.7334, "Dusseldorf", "DUS", "ibis Dusseldorf Hauptbahnhof", "Hilton Dusseldorf", "Breidenbacher Hof"],
  "Hannover": ["Hannover", "Germany", 52.3600, 9.7314, "Hannover", "HAJ", "ibis Hannover City", "Sheraton Hannover Pelikan Hotel", "Kastens Hotel Luisenhof"],
  "Nurnberg": ["Nuremberg", "Germany", 49.4262, 11.1257, "Nuremberg", "NUE", "ibis Nurnberg Altstadt", "Sheraton Carlton Nurnberg", "Hotel Drei Raben"],
  "Karlsruhe": ["Karlsruhe", "Germany", 49.0202, 8.4132, "Karlsruhe/Baden-Baden", "FKB", "ibis Karlsruhe Hauptbahnhof", "Novotel Karlsruhe City", "Schlosshotel Karlsruhe"],
  "Paderborn": ["Paderborn", "Germany", 51.7142, 8.7111, "Paderborn Lippstadt", "PAD", "B&B Hotel Paderborn", "Welcome Hotel Paderborn", "Graflicher Park Health and Balance Resort, Bad Driburg"],

  // ---------- Ligue 2 ----------
  "Saint-Etienne": ["Saint-Etienne", "France", 45.4608, 4.3903, "Lyon Saint-Exupery", "LYS", "ibis Saint-Etienne Gare Chateaucreux", "Mercure Saint-Etienne Centre Parc de l'Europe", "Villa Florentine, Lyon"],
  "Montpellier": ["Montpellier", "France", 43.6222, 3.8119, "Montpellier Mediterranee", "MPL", "ibis Montpellier Centre Comedie", "Pullman Montpellier Centre", "Domaine de Verchant"],
  "Reims": ["Reims", "France", 49.2467, 4.0250, "Paris Charles de Gaulle", "CDG", "ibis Reims Centre", "Mercure Reims Centre Cathedrale", "Domaine Les Crayeres"],
  "Bordeaux": ["Bordeaux", "France", 44.8975, -0.5614, "Bordeaux Merignac", "BOD", "ibis Bordeaux Centre Meriadeck", "Mercure Bordeaux Centre Gare Saint-Jean", "InterContinental Bordeaux Le Grand Hotel"],
  "Caen": ["Caen", "France", 49.1797, -0.3967, "Caen Carpiquet", "CFR", "ibis Caen Centre", "Mercure Caen Centre Port de Plaisance", "Chateau d'Audrieu"],
  "Bastia": ["Bastia", "France", 42.6519, 9.4442, "Bastia Poretta", "BIA", "ibis Styles Bastia", "Hotel Les Voyageurs Bastia", "Hotel des Gouverneurs Bastia"],
  "Grenoble": ["Grenoble", "France", 45.1872, 5.7415, "Grenoble Alpes Isere", "GNB", "ibis Grenoble Centre Bastille", "Mercure Grenoble Centre President", "Le Grand Hotel Grenoble"],
  "Amiens": ["Amiens", "France", 49.8942, 2.2634, "Paris Charles de Gaulle", "CDG", "ibis Amiens Centre Cathedrale", "Mercure Amiens Cathedrale", "Hotel Marotte Amiens"]
};

if (typeof module !== "undefined" && module.exports) module.exports = { TRAVEL };
